# -*- coding: utf-8 -*-
"""
03_adaptive_basis_rve_builder.py

Adaptive basis-RVE builder for 20x20x20 periodic CPFE training RVEs.

This version supports multi-core candidate evaluation and six Ndiff groups.

What this script does
---------------------
1. Reads a periodic element-neighbor map produced from the 20^3 template INP.
2. Generates multiple candidate periodic phase fields per round.
3. Calculates periodic N_diff for each candidate.
4. Temporarily assigns phase-specific orientation seeds according to current coverage gaps.
5. Evaluates four convergence/coverage metrics:
      C_PN          : Phase x exact-N_diff effective coverage
      C_PO          : Phase x Orientation effective coverage
      R_ge_4        : percentage of orientation seeds appearing in at least four Ndiff groups
      N_undercovered: number of Phase x N_diff states below the effective-count threshold

   Weight diagnostics are still printed and saved, but capped W95 is no longer
   used as a main convergence metric because rare BCC-high-N_diff states can
   keep raw weights very large under the prescribed BCC/HCP = 8:2 phase ratio.
6. Accepts the best candidate as the next RVE.
7. Saves one folder per accepted RVE, plus global coverage history and dashboard figures.

Important
---------
This script DOES NOT generate Abaqus INP files.
It only generates the information needed later for INP injection:
    Element_ID, Phase, N_diff, Eta, Orientation_ID, phi1, Phi, phi2, Sample_Weight, etc.

Expected orientation pool CSV format
------------------------------------
Columns required:
    Orientation_ID, phi1, Phi, phi2

Phase convention
----------------
    BCC = 1
    HCP = 9

Author: generated for CPFE adaptive basis-RVE workflow
"""

from __future__ import annotations

import ast
import json
import math
import os
import random
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from scipy.ndimage import gaussian_filter, label as nd_label
except Exception:
    gaussian_filter = None
    nd_label = None


# =============================================================================
# CONFIGURATION AREA
# =============================================================================

@dataclass
class Config:
    # --- Input paths ---
    # Periodic neighbor map generated by build_periodic_neighbor_map.py
    NEIGHBOR_MAP_CSV: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\01_neibor_read_file\element_periodic_neighbor_map.csv"

    # Orientation pools. Each CSV needs: Orientation_ID, phi1, Phi, phi2
    BCC_ORIENTATION_POOL_CSV: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\02_generate_orientation_pools_file\BCC_orientation_pool.csv"
    HCP_ORIENTATION_POOL_CSV: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\02_generate_orientation_pools_file\HCP_orientation_pool.csv"

    # If True, dummy orientation pools are generated when CSVs are not supplied.
    # Use this only for testing the workflow. For final data, set to False and provide real pools.
    ALLOW_DUMMY_ORIENTATION_POOL: bool = False
    DUMMY_BCC_ORIENTATION_COUNT: int = 311
    DUMMY_HCP_ORIENTATION_COUNT: int = 325

    # --- Output path ---
    OUTPUT_ROOT: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\03_adaptive_basis_rve_builder_file"
    CLEAR_OUTPUT_ROOT_ON_START: bool = False

    # --- RVE geometry / phase settings ---
    NX: int = 20
    NY: int = 20
    NZ: int = 20
    BCC_PHASE_ID: int = 1
    HCP_PHASE_ID: int = 9
    N_TOTAL_NEIGHBORS: int = 26

    # Training RVEs are sampling RVEs, not statistically representative RVEs.
    # Therefore no physical BCC:HCP ratio (e.g. 8:2) is imposed.
    # The background phase fraction is randomized only to generate diverse phase
    # topologies; targeted motifs below are then inserted according to coverage gaps.
    RANDOM_HCP_FRACTION_MIN: float = 0.05
    RANDOM_HCP_FRACTION_MAX: float = 0.95

    # --- Adaptive generation settings ---
    RANDOM_SEED: int = 20260708
    MAX_RVE_COUNT: int = 12
    CANDIDATES_PER_ROUND: int = 40

    # Number of CPU worker processes used to evaluate candidate RVEs in parallel.
    # Set to 1 for the original single-core mode. On Windows, keep this script
    # under if __name__ == "__main__"; this file already does that.
    N_CPU_WORKERS: int = 4

    INTERACTIVE_MODE: bool = True      # ask user after each accepted RVE
    AUTO_STOP_ENABLED: bool = False    # if True, stop automatically when criteria are met

    # Candidate field families.
    # sigma controls phase-field correlation length. Larger sigma -> larger clusters.
    SIGMA_LIST: Tuple[float, ...] = (3.0, 2.0, 1.0, 0.55)
    FAMILY_NAMES: Tuple[str, ...] = (
        "HCP_CLUSTERED",
        "BCC_CLUSTERED",
        "MEDIUM_CLUSTERED",
        "INTERFACE_ENRICHED",
        "MIXED_FRAGMENTED",
        "BCC_IN_HCP_INCLUSION",
    )

    # --- Coverage-driven Phase x N_diff repair ---
    # Priority 1: every Phase x exact-N_diff state must exist at least once.
    # Priority 2: after existence is complete, preferentially add the currently
    #             least-covered states until the effective-count threshold is reached.
    PRIORITY_REPAIR_ENABLED: bool = True
    PRIORITY_REPAIR_START_ROUND: int = 1

    # Hard existence requirement. With two phases and N_diff=0..26 there are 54 states.
    EXISTENCE_MIN_COUNT: int = 1
    MAX_EXISTENCE_TARGETS_PER_RVE: int = 54

    # After all 54 states exist, target the most undercovered states first.
    MAX_BALANCE_TARGETS_PER_RVE: int = 12

    # Once every state also reaches N_MIN_PHASE_NDIFF, continue relative equalization.
    # A Phase x N_diff state is considered low relative to its own phase when
    # count < (1 - EQUALIZE_REL_TOL) * phase_mean_count.
    EQUALIZE_REL_TOL: float = 0.10
    MAX_EQUALIZE_TARGETS_PER_RVE: int = 12

    # Number of protected 3x3x3 motifs inserted for a target state.
    # In existence stage, one motif is sufficient to guarantee at least one center state.
    EXISTENCE_MOTIFS_PER_STATE: int = 1
    # In balancing stage, several motifs may be inserted for the same deficient state.
    BALANCE_MAX_MOTIFS_PER_STATE: int = 5

    # Target motifs are spatially separated so their 3x3x3 neighborhoods do not overlap.
    REPAIR_MIN_CENTER_DISTANCE: int = 4

    # Candidate score terms.
    SCORE_W_NEW_STATE_FILL: float = 25.0
    SCORE_W_PRIORITY_REPAIR: float = 8.0

    # Reward reduction of Phase-wise PN imbalance, and penalize a candidate that
    # keeps adding many elements to states that were already above the phase mean.
    SCORE_W_BALANCE_IMPROVEMENT: float = 6.0
    SCORE_W_OVERCOVERAGE_PENALTY: float = 3.0

    # A state is treated as already overrepresented when its cumulative count is
    # above (1 + OVERCOVER_REL_TOL) * the mean count of its own phase.
    OVERCOVER_REL_TOL: float = 0.10

    # Do not allow manual/automatic stopping while any Phase x N_diff state is absent.
    REQUIRE_FULL_PN_EXISTENCE_BEFORE_STOP: bool = True

    # --- Metric thresholds ---
    # A Phase-Ndiff state is effectively covered only if count >= N_MIN.
    N_MIN_PHASE_NDIFF: int = 50
    # A phase-specific orientation seed is effectively covered only if count >= O_MIN.
    O_MIN_ORIENTATION: int = 5
    # An Orientation-Ndiff_group pair is considered present only if count >= G_MIN.
    G_MIN_ORI_GROUP: int = 3

    # Ndiff groups used for orientation-neighbor decoupling.
    # Format: name, lower_bound, upper_bound, inclusive.
    # Six Ndiff groups used for orientation-neighbor decoupling.
    # C_PN still uses the exact N_diff states 0..26; these groups are only used
    # for Orientation x Ndiff_Group assignment and R_ge_2..R_ge_6 diagnostics.
    NDIFF_GROUPS: Tuple[Tuple[str, int, int], ...] = (
        ("zero", 0, 0),
        ("low", 1, 4),
        ("lower_medium", 5, 9),
        ("upper_medium", 10, 16),
        ("high", 17, 25),
        ("full", 26, 26),
    )

    # --- Stop criteria ---
    STOP_DCPN: float = 0.02   # C_PN improvement < 2%
    STOP_DCPO: float = 0.01   # C_PO improvement < 1%
    STOP_DRGE4: float = 0.02  # R_ge_4 improvement < 2%

    # Because W95 is capped and may stay at WEIGHT_CAP when extreme states are
    # inherently rare, the fourth main stop criterion uses the reduction in the
    # number of undercovered Phase x N_diff states instead of W95 variation.
    STOP_DUNDERCOVERED_REDUCTION_MAX: int = 1
    STOP_REQUIRE_CONSECUTIVE: int = 1  # set 2 if you want stricter plateau criterion

    # --- Weight settings ---
    # Default: no hard cap. For each phase, w(phase,N_diff)=max_count/count.
    # Once all 27 N_diff states exist, the weighted distribution within that phase
    # is exactly flat in Phase x N_diff space.
    USE_WEIGHT_CAP: bool = False
    WEIGHT_CAP: float = 20.0   # only used if USE_WEIGHT_CAP=True

    # --- Candidate scoring weights ---
    SCORE_W_CPN: float = 2.0
    SCORE_W_CPO: float = 1.0
    SCORE_W_RGE4: float = 2.0

    # Capped W95 is kept as a diagnostic and for output Sample_Weight control,
    # but its default score weight is zero because it can be saturated by rare
    # extreme BCC-high-N_diff states.
    SCORE_W_W95: float = 0.0
    SCORE_W_MARGINAL_PN: float = 0.05
    SCORE_W_SHAPE_PENALTY: float = 0.05
    SCORE_W_SIMILARITY_PENALTY: float = 0.05

    # No phase-specific prior is used: BCC and HCP states are treated symmetrically.
    PRIOR_DEFAULT: float = 1.0

    # Plot settings
    SAVE_DASHBOARD_EACH_ROUND: bool = True
    SHOW_DASHBOARD: bool = False  # True requires a GUI backend; usually False on clusters


CFG = Config()


# =============================================================================
# Utility functions
# =============================================================================

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def parse_neighbor_list(x) -> List[int]:
    if isinstance(x, list):
        return [int(v) for v in x]
    if isinstance(x, str):
        return [int(v) for v in ast.literal_eval(x)]
    raise ValueError("Unsupported Neighbor_List format: %r" % type(x))


def load_neighbor_map(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"Element_ID", "i", "j", "k", "Neighbor_List"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError("Neighbor map missing columns: %s" % sorted(missing))
    df["Neighbor_List"] = df["Neighbor_List"].apply(parse_neighbor_list)
    df = df.sort_values("Element_ID").reset_index(drop=True)
    return df


def load_orientation_pool(path: str, phase_name: str, dummy_count: int, allow_dummy: bool) -> pd.DataFrame:
    if path and os.path.exists(path):
        df = pd.read_csv(path)
        required = {"Orientation_ID", "phi1", "Phi", "phi2"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError("%s orientation pool missing columns: %s" % (phase_name, sorted(missing)))
        df = df[["Orientation_ID", "phi1", "Phi", "phi2"]].copy()
        df["Orientation_ID"] = df["Orientation_ID"].astype(str)
        return df

    if not allow_dummy:
        raise FileNotFoundError(
            "%s orientation pool not found. Set %s_ORIENTATION_POOL_CSV or enable dummy mode." %
            (phase_name, phase_name)
        )

    # Dummy pool: useful for testing the adaptive workflow only.
    # Euler angles are NaN so the user cannot accidentally use them as final orientations.
    return pd.DataFrame({
        "Orientation_ID": ["%s_%04d" % (phase_name, i + 1) for i in range(dummy_count)],
        "phi1": np.nan,
        "Phi": np.nan,
        "phi2": np.nan,
    })


def ndiff_group(n: int, groups: Tuple[Tuple[str, int, int], ...]) -> str:
    for name, lo, hi in groups:
        if lo <= int(n) <= hi:
            return name
    return "out_of_range"


def phase_label(phase: int, cfg: Config) -> str:
    if int(phase) == cfg.BCC_PHASE_ID:
        return "BCC"
    if int(phase) == cfg.HCP_PHASE_ID:
        return "HCP"
    return str(phase)


# =============================================================================
# Phase-field generation
# =============================================================================

def exact_hcp_threshold(field: np.ndarray, hcp_count: int) -> np.ndarray:
    """Return boolean mask with exactly hcp_count True values at the largest field values."""
    flat = field.ravel()
    if hcp_count <= 0 or hcp_count >= flat.size:
        raise ValueError("Invalid hcp_count: %d" % hcp_count)
    idx = np.argpartition(flat, -hcp_count)[-hcp_count:]
    mask = np.zeros(flat.size, dtype=bool)
    mask[idx] = True
    return mask.reshape(field.shape)


def periodic_distance_sq_grid(nx: int, ny: int, nz: int, cx: float, cy: float, cz: float) -> np.ndarray:
    x = np.arange(nx)[:, None, None]
    y = np.arange(ny)[None, :, None]
    z = np.arange(nz)[None, None, :]
    dx = np.minimum(np.abs(x - cx), nx - np.abs(x - cx))
    dy = np.minimum(np.abs(y - cy), ny - np.abs(y - cy))
    dz = np.minimum(np.abs(z - cz), nz - np.abs(z - cz))
    return dx * dx + dy * dy + dz * dz


def generate_cluster_field(nx: int, ny: int, nz: int, rng: np.random.Generator,
                           n_centers: int = 3, radius: float = 4.0) -> np.ndarray:
    field = np.zeros((nx, ny, nz), dtype=float)
    for _ in range(n_centers):
        cx = rng.uniform(0, nx)
        cy = rng.uniform(0, ny)
        cz = rng.uniform(0, nz)
        dist2 = periodic_distance_sq_grid(nx, ny, nz, cx, cy, cz)
        field += np.exp(-dist2 / (2.0 * radius * radius))
    field += 0.05 * rng.normal(size=(nx, ny, nz))
    return field


def generate_candidate_phase_field(cfg: Config, rng: np.random.Generator, family: str) -> Tuple[np.ndarray, Dict]:
    """Generate one candidate phase array without imposing a physical phase ratio.

    A broad random HCP fraction is used only as a background-topology generator.
    It is not a material constraint and is not rebalanced after targeted motifs
    are inserted.
    """
    nx, ny, nz = cfg.NX, cfg.NY, cfg.NZ
    n_elem = nx * ny * nz

    fmin = float(cfg.RANDOM_HCP_FRACTION_MIN)
    fmax = float(cfg.RANDOM_HCP_FRACTION_MAX)
    if not (0.0 < fmin < fmax < 1.0):
        raise ValueError("Require 0 < RANDOM_HCP_FRACTION_MIN < RANDOM_HCP_FRACTION_MAX < 1.")

    hcp_fraction = float(rng.uniform(fmin, fmax))
    hcp_count = int(round(n_elem * hcp_fraction))
    hcp_count = max(1, min(n_elem - 1, hcp_count))

    info = {
        "family": family,
        "background_hcp_fraction_requested": hcp_fraction,
    }

    if family == "HCP_CLUSTERED":
        field = generate_cluster_field(
            nx, ny, nz, rng,
            n_centers=int(rng.integers(1, 3)),
            radius=float(rng.uniform(3.8, 5.8))
        )

    elif family == "BCC_CLUSTERED":
        # Negating the field makes the clustered low-field region preferentially BCC.
        field = -generate_cluster_field(
            nx, ny, nz, rng,
            n_centers=int(rng.integers(1, 3)),
            radius=float(rng.uniform(3.8, 5.8))
        )

    elif family == "MEDIUM_CLUSTERED":
        if gaussian_filter is None:
            field = rng.normal(size=(nx, ny, nz))
        else:
            field = gaussian_filter(
                rng.normal(size=(nx, ny, nz)),
                sigma=float(rng.choice([1.6, 2.0, 2.4])),
                mode="wrap"
            )

    elif family == "INTERFACE_ENRICHED":
        if gaussian_filter is None:
            field = rng.normal(size=(nx, ny, nz))
        else:
            field = gaussian_filter(
                rng.normal(size=(nx, ny, nz)),
                sigma=float(rng.choice([0.7, 0.9, 1.1])),
                mode="wrap"
            )

    elif family == "MIXED_FRAGMENTED":
        if gaussian_filter is None:
            field = rng.normal(size=(nx, ny, nz))
        else:
            field1 = gaussian_filter(rng.normal(size=(nx, ny, nz)), sigma=2.5, mode="wrap")
            field2 = gaussian_filter(rng.normal(size=(nx, ny, nz)), sigma=0.6, mode="wrap")
            field = 0.65 * field1 + 0.35 * field2

    elif family == "BCC_IN_HCP_INCLUSION":
        field = generate_cluster_field(
            nx, ny, nz, rng,
            n_centers=int(rng.integers(1, 3)),
            radius=float(rng.uniform(4.0, 6.0))
        )
        prelim = exact_hcp_threshold(field, hcp_count)
        hcp_positions = np.argwhere(prelim)
        if len(hcp_positions) > 0:
            for _ in range(int(rng.integers(4, 10))):
                px, py, pz = hcp_positions[int(rng.integers(0, len(hcp_positions)))]
                dist2 = periodic_distance_sq_grid(nx, ny, nz, px, py, pz)
                pocket_radius = float(rng.uniform(0.8, 1.5))
                field -= float(rng.uniform(0.8, 1.4)) * np.exp(
                    -dist2 / (2.0 * pocket_radius * pocket_radius)
                )

    else:
        sigma = float(rng.choice(cfg.SIGMA_LIST))
        info["sigma"] = sigma
        if gaussian_filter is None:
            field = rng.normal(size=(nx, ny, nz))
        else:
            field = gaussian_filter(rng.normal(size=(nx, ny, nz)), sigma=sigma, mode="wrap")

    hcp_mask = exact_hcp_threshold(field, hcp_count)
    phase = np.full((nx, ny, nz), cfg.BCC_PHASE_ID, dtype=np.int16)
    phase[hcp_mask] = cfg.HCP_PHASE_ID

    info["hcp_count"] = int(hcp_mask.sum())
    info["bcc_count"] = int(n_elem - hcp_mask.sum())
    info["hcp_fraction_actual"] = float(hcp_mask.mean())
    return phase, info


def periodic_chebyshev_distance(a: Tuple[int, int, int], b: Tuple[int, int, int],
                                nx: int, ny: int, nz: int) -> int:
    """Periodic Chebyshev distance between two integer grid points."""
    dx = min(abs(a[0] - b[0]), nx - abs(a[0] - b[0]))
    dy = min(abs(a[1] - b[1]), ny - abs(a[1] - b[1]))
    dz = min(abs(a[2] - b[2]), nz - abs(a[2] - b[2]))
    return int(max(dx, dy, dz))


def neighbor_offsets_26() -> List[Tuple[int, int, int]]:
    return [(di, dj, dk)
            for dk in (-1, 0, 1)
            for dj in (-1, 0, 1)
            for di in (-1, 0, 1)
            if not (di == 0 and dj == 0 and dk == 0)]


def choose_repair_centers(cfg: Config,
                          rng: np.random.Generator,
                          n_centers: int) -> List[Tuple[int, int, int]]:
    """Choose separated motif centers using periodic Chebyshev distance."""
    centers: List[Tuple[int, int, int]] = []
    max_trials = max(20000, 500 * int(n_centers))

    for _ in range(max_trials):
        if len(centers) >= int(n_centers):
            break

        c = (
            int(rng.integers(0, cfg.NX)),
            int(rng.integers(0, cfg.NY)),
            int(rng.integers(0, cfg.NZ)),
        )

        if all(
            periodic_chebyshev_distance(
                c, old, cfg.NX, cfg.NY, cfg.NZ
            ) >= int(cfg.REPAIR_MIN_CENTER_DISTANCE)
            for old in centers
        ):
            centers.append(c)

    if len(centers) < int(n_centers):
        raise RuntimeError(
            "Could not place %d non-overlapping targeted motifs with "
            "REPAIR_MIN_CENTER_DISTANCE=%d. Placed only %d."
            % (int(n_centers), int(cfg.REPAIR_MIN_CENTER_DISTANCE), len(centers))
        )

    return centers


def get_priority_pn_targets(current_counts: Dict,
                            cfg: Config,
                            round_k: int) -> Tuple[str, List[Tuple[int, int, int]]]:
    """Return coverage-driven target states for the next candidate RVE.

    Returns
    -------
    stage : "existence", "balance", "equalize", or "none"
    targets : [(phase, N_diff, need), ...]

    Existence stage:
        Every Phase x exact-N_diff state must reach EXISTENCE_MIN_COUNT.
        Missing states are targeted before any balancing objective.

    Balance stage:
        Once all states exist, the states with the smallest cumulative counts are
        prioritized toward N_MIN_PHASE_NDIFF.

    Equalize stage:
        Once all states reach N_MIN_PHASE_NDIFF, states that remain substantially
        below the mean count of their own phase are preferentially targeted.
    """
    if not cfg.PRIORITY_REPAIR_ENABLED:
        return "none", []
    if int(round_k) < int(cfg.PRIORITY_REPAIR_START_ROUND):
        return "none", []

    pn = current_counts["PN"]

    missing: List[Tuple[int, int, int, int]] = []
    for (phase, nd), value in pn.items():
        c = int(value)
        if c < int(cfg.EXISTENCE_MIN_COUNT):
            need = int(cfg.EXISTENCE_MIN_COUNT) - c
            missing.append((c, int(nd), int(phase), need))

    if missing:
        # Lower current count first; then N_diff; then phase for deterministic ordering.
        missing.sort(key=lambda x: (x[0], x[1], x[2]))
        selected = missing[:int(cfg.MAX_EXISTENCE_TARGETS_PER_RVE)]
        targets = [(phase, nd, need) for _, nd, phase, need in selected]
        return "existence", targets

    under: List[Tuple[int, int, int, int]] = []
    for (phase, nd), value in pn.items():
        c = int(value)
        if c < int(cfg.N_MIN_PHASE_NDIFF):
            need = int(cfg.N_MIN_PHASE_NDIFF) - c
            under.append((c, int(nd), int(phase), need))

    if under:
        # The least-covered states are always served first.
        under.sort(key=lambda x: (x[0], x[1], x[2]))
        selected = under[:int(cfg.MAX_BALANCE_TARGETS_PER_RVE)]
        targets = [(phase, nd, need) for _, nd, phase, need in selected]
        return "balance", targets

    # Relative equalization stage:
    # all states already satisfy N_MIN_PHASE_NDIFF, but some states may still be
    # much lower than the mean count of their own phase.
    equalize: List[Tuple[float, int, int, int]] = []
    tol = float(cfg.EQUALIZE_REL_TOL)

    for phase in [cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID]:
        sub = pn.loc[phase]
        phase_mean = float(sub.mean())

        if phase_mean <= 0.0:
            continue

        target_level = (1.0 - tol) * phase_mean

        for nd, value in sub.items():
            c = float(value)

            if c < target_level:
                need = max(1, int(math.ceil(target_level - c)))
                relative_level = c / (phase_mean + 1.0e-12)
                equalize.append(
                    (relative_level, int(nd), int(phase), int(need))
                )

    if equalize:
        # Smallest relative count first, independently of the global phase ratio.
        equalize.sort(key=lambda x: (x[0], x[1], x[2]))
        selected = equalize[:int(cfg.MAX_EQUALIZE_TARGETS_PER_RVE)]
        targets = [(phase, nd, need) for _, nd, phase, need in selected]
        return "equalize", targets

    return "none", []


def build_target_motif_requests(stage: str,
                                targets: List[Tuple[int, int, int]],
                                cfg: Config) -> List[Tuple[int, int, int]]:
    """Expand target states into individual motif requests.

    Each request is (phase, N_diff, target_need).
    """
    requests: List[Tuple[int, int, int]] = []

    for phase, nd, need in targets:
        if stage == "existence":
            n_motifs = int(cfg.EXISTENCE_MOTIFS_PER_STATE)
        else:
            n_motifs = min(
                int(cfg.BALANCE_MAX_MOTIFS_PER_STATE),
                max(1, int(need)),
            )

        for _ in range(n_motifs):
            requests.append((int(phase), int(nd), int(need)))

    return requests


def generate_priority_repair_phase_field(cfg: Config,
                                         rng: np.random.Generator,
                                         stage: str,
                                         targets: List[Tuple[int, int, int]]) -> Tuple[np.ndarray, Dict]:
    """Generate one phase field that explicitly embeds multiple deficient states.

    A target motif is a 3x3x3 periodic block whose center has the requested phase
    and whose 26 neighbors contain exactly target_ndiff opposite-phase cells.
    Motifs are separated so one motif cannot overwrite another motif's center
    neighborhood. No phase-fraction rebalance is applied afterward.
    """
    background_family = str(rng.choice(cfg.FAMILY_NAMES))
    phase, base_info = generate_candidate_phase_field(cfg, rng, background_family)

    requests = build_target_motif_requests(stage, targets, cfg)
    if not requests:
        return phase, base_info

    centers = choose_repair_centers(cfg, rng, len(requests))
    offsets = neighbor_offsets_26()

    target_records = []

    for center, (target_phase, target_ndiff, target_need) in zip(centers, requests):
        if not (0 <= int(target_ndiff) <= int(cfg.N_TOTAL_NEIGHBORS)):
            raise ValueError("target_ndiff must be in [0, 26].")

        other_phase = (
            cfg.HCP_PHASE_ID
            if int(target_phase) == int(cfg.BCC_PHASE_ID)
            else cfg.BCC_PHASE_ID
        )

        ci, cj, ck = center
        phase[ci, cj, ck] = int(target_phase)

        # Randomize which neighbor directions are opposite phase.
        order = np.arange(len(offsets))
        rng.shuffle(order)
        other_idx = set(int(x) for x in order[:int(target_ndiff)])

        for m, (di, dj, dk) in enumerate(offsets):
            ni = (ci + di) % cfg.NX
            nj = (cj + dj) % cfg.NY
            nk = (ck + dk) % cfg.NZ
            phase[ni, nj, nk] = (
                int(other_phase) if m in other_idx else int(target_phase)
            )

        target_records.append({
            "phase": int(target_phase),
            "N_diff": int(target_ndiff),
            "need_before_candidate": int(target_need),
            "center": [int(ci), int(cj), int(ck)],
        })

    n_elem = int(cfg.NX * cfg.NY * cfg.NZ)
    hcp_count = int((phase == cfg.HCP_PHASE_ID).sum())

    info = {
        "family": "COVERAGE_DRIVEN_TARGETED",
        "background_family": base_info.get("family", background_family),
        "priority_stage": stage,
        "n_target_states": int(len(targets)),
        "n_target_motifs": int(len(requests)),
        "target_records": target_records,
        "hcp_count": hcp_count,
        "bcc_count": n_elem - hcp_count,
        "hcp_fraction_actual": float(hcp_count) / float(n_elem),
    }
    return phase, info


def phase_grid_to_element_phase(neighbor_df: pd.DataFrame, phase_grid: np.ndarray) -> np.ndarray:
    phases = np.empty(len(neighbor_df), dtype=np.int16)
    for row_i, row in neighbor_df.iterrows():
        phases[row_i] = phase_grid[int(row["i"]), int(row["j"]), int(row["k"])]
    return phases


def compute_n_diff(phases: np.ndarray, neighbor_lists: List[List[int]], elem_id_to_pos: Dict[int, int]) -> np.ndarray:
    ndiff = np.zeros(len(phases), dtype=np.int16)
    for pos, nbr_ids in enumerate(neighbor_lists):
        p = phases[pos]
        cnt = 0
        for nid in nbr_ids:
            npos = elem_id_to_pos[int(nid)]
            if phases[npos] != p:
                cnt += 1
        ndiff[pos] = cnt
    return ndiff


# =============================================================================
# Coverage statistics and metrics
# =============================================================================

def empty_counts(cfg: Config, bcc_pool: pd.DataFrame, hcp_pool: pd.DataFrame) -> Dict:
    phases = [cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID]
    ndiffs = list(range(0, cfg.N_TOTAL_NEIGHBORS + 1))
    groups = [g[0] for g in cfg.NDIFF_GROUPS]

    pn = pd.Series(0, index=pd.MultiIndex.from_product([phases, ndiffs], names=["Phase", "N_diff"]), dtype=float)

    po_index = []
    for p, pool in [(cfg.BCC_PHASE_ID, bcc_pool), (cfg.HCP_PHASE_ID, hcp_pool)]:
        for oid in pool["Orientation_ID"].astype(str):
            po_index.append((p, oid))
    po = pd.Series(0, index=pd.MultiIndex.from_tuples(po_index, names=["Phase", "Orientation_ID"]), dtype=float)

    pog_index = []
    for p, pool in [(cfg.BCC_PHASE_ID, bcc_pool), (cfg.HCP_PHASE_ID, hcp_pool)]:
        for oid in pool["Orientation_ID"].astype(str):
            for g in groups:
                pog_index.append((p, oid, g))
    pog = pd.Series(0, index=pd.MultiIndex.from_tuples(pog_index, names=["Phase", "Orientation_ID", "Ndiff_Group"]), dtype=float)

    return {"PN": pn, "PO": po, "POG": pog}


def counts_from_rve(df: pd.DataFrame, cfg: Config, bcc_pool: pd.DataFrame, hcp_pool: pd.DataFrame) -> Dict:
    counts = empty_counts(cfg, bcc_pool, hcp_pool)

    pn_counts = df.groupby(["Phase", "N_diff"]).size()
    counts["PN"].loc[pn_counts.index] = pn_counts.astype(float)

    po_counts = df.groupby(["Phase", "Orientation_ID"]).size()
    common = counts["PO"].index.intersection(po_counts.index)
    counts["PO"].loc[common] = po_counts.loc[common].astype(float)

    pog_counts = df.groupby(["Phase", "Orientation_ID", "Ndiff_Group"]).size()
    common = counts["POG"].index.intersection(pog_counts.index)
    counts["POG"].loc[common] = pog_counts.loc[common].astype(float)

    return counts


def add_counts(a: Dict, b: Dict) -> Dict:
    return {"PN": a["PN"].add(b["PN"], fill_value=0),
            "PO": a["PO"].add(b["PO"], fill_value=0),
            "POG": a["POG"].add(b["POG"], fill_value=0)}


def compute_state_weights_raw_and_used(pn_counts: pd.Series,
                                       cfg: Config) -> Tuple[pd.Series, pd.Series]:
    """Return raw and actually-used Phase x N_diff weights.

    Within each phase:
        w_raw(phase, n) = max_count_phase / count(phase, n)

    Therefore, for every existing state:
        count * weight = max_count_phase

    If all 27 N_diff states exist, the weighted N_diff distribution within each
    phase is exactly flat. Zero-count states are stored as NaN because weighting
    cannot create a state that does not exist; the coverage-driven generator must
    create those states first.

    By default USE_WEIGHT_CAP=False, so used weight equals raw weight.
    """
    raw = pn_counts.copy().astype(float)
    used = pn_counts.copy().astype(float)

    for phase in [cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID]:
        sub = pn_counts.loc[phase]
        nonzero = sub[sub > 0]

        if len(nonzero) == 0:
            raw.loc[phase] = np.nan
            used.loc[phase] = np.nan
            continue

        max_count = float(nonzero.max())

        for nd in sub.index:
            c = float(sub.loc[nd])

            if c <= 0:
                w_raw = np.nan
                w_used = np.nan
            else:
                w_raw = max_count / c
                if bool(cfg.USE_WEIGHT_CAP):
                    w_used = min(float(w_raw), float(cfg.WEIGHT_CAP))
                else:
                    w_used = float(w_raw)

            raw.loc[(phase, nd)] = w_raw
            used.loc[(phase, nd)] = w_used

    return raw, used


def compute_state_weights_from_pn(pn_counts: pd.Series, cfg: Config) -> pd.Series:
    """Return the actual Sample_Weight series used by downstream CPFE/ML files."""
    _, used = compute_state_weights_raw_and_used(pn_counts, cfg)
    return used


# Backward-compatible helper name used by old plotting/output code.
def compute_state_weights_raw_and_capped(pn_counts: pd.Series,
                                         cfg: Config) -> Tuple[pd.Series, pd.Series]:
    return compute_state_weights_raw_and_used(pn_counts, cfg)


def compute_weight_diagnostics(pn_counts: pd.Series, cfg: Config) -> Dict[str, float]:
    raw, used = compute_state_weights_raw_and_used(pn_counts, cfg)

    nonzero_mask = pn_counts > 0
    finite_raw = raw[nonzero_mask & raw.notna()]
    finite_used = used[nonzero_mask & used.notna()]

    if len(finite_raw):
        w95_raw = float(np.percentile(finite_raw.values, 95))
        wmax_raw = float(finite_raw.max())
    else:
        w95_raw = float("nan")
        wmax_raw = float("nan")

    if len(finite_used):
        w95_used = float(np.percentile(finite_used.values, 95))
        wmax_used = float(finite_used.max())
    else:
        w95_used = float("nan")
        wmax_used = float("nan")

    if bool(cfg.USE_WEIGHT_CAP):
        cap_hit_nonzero = int((finite_raw >= float(cfg.WEIGHT_CAP)).sum())
        n_nonzero = int(nonzero_mask.sum())
        cap_hit_ratio = float(cap_hit_nonzero) / float(n_nonzero) if n_nonzero else 0.0
    else:
        cap_hit_nonzero = 0
        cap_hit_ratio = 0.0

    zero_states = int((pn_counts <= 0).sum())
    undercovered_states = int((pn_counts < cfg.N_MIN_PHASE_NDIFF).sum())
    effective_states = int((pn_counts >= cfg.N_MIN_PHASE_NDIFF).sum())

    # Total count deficit toward the effective-count target.
    total_deficit = int(
        sum(max(0, int(cfg.N_MIN_PHASE_NDIFF) - int(c)) for c in pn_counts.values)
    )

    return {
        "W95": w95_used,
        "W95_capped": w95_used,       # backward-compatible column name
        "W95_used": w95_used,
        "Wmax": wmax_used,
        "Wmax_capped": wmax_used,     # backward-compatible column name
        "Wmax_used": wmax_used,
        "W95_raw": w95_raw,
        "Wmax_raw": wmax_raw,
        "Cap_hit_states": cap_hit_nonzero,
        "Cap_hit_ratio": cap_hit_ratio,
        "Zero_PN_states": zero_states,
        "N_undercovered": undercovered_states,
        "N_effectively_covered": effective_states,
        "PN_total_deficit": total_deficit,
    }


def compute_metrics(counts: Dict, cfg: Config) -> Dict[str, float]:
    pn = counts["PN"]
    po = counts["PO"]
    pog = counts["POG"]

    # C_PN: effective Phase x exact-N_diff coverage
    c_pn = float((pn >= cfg.N_MIN_PHASE_NDIFF).sum()) / float(len(pn))

    # C_PO: effective Phase x Orientation coverage
    c_po = float((po >= cfg.O_MIN_ORIENTATION).sum()) / float(len(po)) if len(po) else 0.0

    # Orientation-Ndiff_group decoupling: how many group classes each orientation covers.
    present = (pog >= cfg.G_MIN_ORI_GROUP).astype(int)
    group_counts = present.groupby(level=["Phase", "Orientation_ID"]).sum()
    denom = float(len(group_counts)) if len(group_counts) else 1.0
    n_groups = len(cfg.NDIFF_GROUPS)
    r_values = {}
    for n in range(2, n_groups + 1):
        r_values["R_ge_%d" % n] = float((group_counts >= n).sum()) / denom if len(group_counts) else 0.0
    mean_group_count = float(group_counts.mean()) if len(group_counts) else 0.0

    # Weight diagnostics. Capped W95 is diagnostic, not the fourth main convergence metric.
    wdiag = compute_weight_diagnostics(pn, cfg)

    # Helpful diagnostics
    pn_values = pn.values.astype(float)
    cv_pn = float(np.std(pn_values) / (np.mean(pn_values) + 1e-12))
    phase_balance = phasewise_pn_balance_cv(pn, cfg)

    out = {
        "C_PN": c_pn,
        "C_PO": c_po,
        "Mean_Group_Count": mean_group_count,
        "CV_PN": cv_pn,
        "CV_PN_BCC": phase_balance["CV_PN_BCC"],
        "CV_PN_HCP": phase_balance["CV_PN_HCP"],
        "CV_PN_PHASE_MEAN": phase_balance["CV_PN_PHASE_MEAN"],
    }
    out.update(r_values)
    # Backward-compatible alias used in older output columns.
    out["R_3"] = out.get("R_ge_3", 0.0)
    out.update(wdiag)
    return out

def prior_weight_for_state(phase: int, nd: int, cfg: Config) -> float:
    # All Phase x N_diff states are treated symmetrically.
    return cfg.PRIOR_DEFAULT


def marginal_pn_gain(old_pn: pd.Series, add_pn: pd.Series, cfg: Config) -> float:
    gain = 0.0
    c0 = 5.0
    for idx in old_pn.index:
        phase, nd = idx
        old = float(old_pn.loc[idx])
        add = float(add_pn.loc[idx]) if idx in add_pn.index else 0.0
        alpha = prior_weight_for_state(int(phase), int(nd), cfg)
        gain += alpha * (math.log(old + add + c0) - math.log(old + c0))
    return gain


def pn_distribution_vector(pn: pd.Series) -> np.ndarray:
    arr = pn.values.astype(float)
    s = arr.sum()
    if s <= 0:
        return np.zeros_like(arr)
    return arr / s


def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    if denom <= 0:
        return 0.0
    return float(np.dot(a, b) / denom)


# =============================================================================
# Orientation assignment
# =============================================================================

def build_pool_dict(bcc_pool: pd.DataFrame, hcp_pool: pd.DataFrame, cfg: Config) -> Dict[int, pd.DataFrame]:
    return {cfg.BCC_PHASE_ID: bcc_pool.copy(), cfg.HCP_PHASE_ID: hcp_pool.copy()}


def assign_orientations_stratified(base_df: pd.DataFrame,
                                   current_counts: Dict,
                                   bcc_pool: pd.DataFrame,
                                   hcp_pool: pd.DataFrame,
                                   cfg: Config,
                                   rng: np.random.Generator) -> pd.DataFrame:
    """
    Assign orientations after Phase and N_diff are fixed.

    Strategy:
    - Group elements by Phase x Ndiff_Group.
    - Within each group, prioritize orientation seeds with low total usage and low usage in that group.
    - Use round-robin to avoid over-concentrating one orientation in one group.
    """
    df = base_df.copy()
    df["Orientation_ID"] = ""
    df["phi1"] = np.nan
    df["Phi"] = np.nan
    df["phi2"] = np.nan

    pool_by_phase = build_pool_dict(bcc_pool, hcp_pool, cfg)
    po_counts = current_counts["PO"].copy()
    pog_counts = current_counts["POG"].copy()

    for phase in [cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID]:
        pool = pool_by_phase[phase]
        pool_ids = pool["Orientation_ID"].astype(str).tolist()
        pool_lookup = pool.set_index("Orientation_ID")

        for gname, _, _ in cfg.NDIFF_GROUPS:
            mask = (df["Phase"] == phase) & (df["Ndiff_Group"] == gname)
            idxs = df.index[mask].tolist()
            if not idxs:
                continue
            rng.shuffle(idxs)

            # Lower score = higher priority.
            orient_scores = []
            for oid in pool_ids:
                total_use = float(po_counts.loc[(phase, oid)]) if (phase, oid) in po_counts.index else 0.0
                group_use = float(pog_counts.loc[(phase, oid, gname)]) if (phase, oid, gname) in pog_counts.index else 0.0
                # total and group terms; group gets more weight to improve Orientation x Ndiff_group decoupling
                score = total_use + 2.5 * group_use + rng.uniform(0.0, 0.01)
                orient_scores.append((score, oid))
            orient_scores.sort(key=lambda x: x[0])
            ordered_ids = [oid for _, oid in orient_scores]

            # Round-robin through priority list.
            for local_i, row_idx in enumerate(idxs):
                oid = ordered_ids[local_i % len(ordered_ids)]
                vals = pool_lookup.loc[oid]
                df.at[row_idx, "Orientation_ID"] = oid
                df.at[row_idx, "phi1"] = vals["phi1"]
                df.at[row_idx, "Phi"] = vals["Phi"]
                df.at[row_idx, "phi2"] = vals["phi2"]

                # update local counts so this candidate does not overuse the same orientation too much
                po_counts.loc[(phase, oid)] = po_counts.loc[(phase, oid)] + 1
                pog_counts.loc[(phase, oid, gname)] = pog_counts.loc[(phase, oid, gname)] + 1

    return df


# =============================================================================
# Candidate construction and scoring
# =============================================================================

def candidate_to_base_df(rve_id: int, neighbor_df: pd.DataFrame, phase_grid: np.ndarray,
                         ndiff: np.ndarray, cfg: Config, candidate_info: Dict) -> pd.DataFrame:
    phases = phase_grid_to_element_phase(neighbor_df, phase_grid)
    df = neighbor_df[["Element_ID", "i", "j", "k"]].copy()
    for col in ["cx", "cy", "cz"]:
        if col in neighbor_df.columns:
            df[col] = neighbor_df[col]
    df["RVE_ID"] = int(rve_id)
    df["Phase"] = phases.astype(int)
    df["N_total"] = cfg.N_TOTAL_NEIGHBORS
    df["N_diff"] = ndiff.astype(int)
    df["Eta"] = df["N_diff"] / float(cfg.N_TOTAL_NEIGHBORS)
    df["Ndiff_Group"] = df["N_diff"].apply(lambda x: ndiff_group(int(x), cfg.NDIFF_GROUPS))
    df["Generator_Type"] = candidate_info.get("family", "UNKNOWN")
    return df


def shape_penalty_from_df(df: pd.DataFrame, cfg: Config) -> float:
    """Mild penalty for extremely narrow or extremely broad Ndiff distributions."""
    # Penalize very large CV of Phase x Ndiff within candidate, but only mildly.
    counts = df.groupby(["Phase", "N_diff"]).size()
    full_index = pd.MultiIndex.from_product(
        [[cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID], range(0, cfg.N_TOTAL_NEIGHBORS + 1)],
        names=["Phase", "N_diff"]
    )
    full = pd.Series(0.0, index=full_index)
    full.loc[counts.index] = counts.astype(float)
    cv = float(full.std() / (full.mean() + 1e-12))
    return cv



def phasewise_pn_balance_cv(pn_counts: pd.Series, cfg: Config) -> Dict[str, float]:
    """Coefficient of variation of exact N_diff counts within each phase.

    Each phase is evaluated independently so no global BCC:HCP ratio is implied.
    Lower is better; zero means all 27 N_diff states in that phase have equal counts.
    """
    out = {}
    cvs = []

    for phase, label in [
        (cfg.BCC_PHASE_ID, "BCC"),
        (cfg.HCP_PHASE_ID, "HCP"),
    ]:
        vals = pn_counts.loc[phase].to_numpy(dtype=float)
        mean = float(np.mean(vals))

        if mean <= 0.0:
            cv = 0.0
        else:
            cv = float(np.std(vals) / (mean + 1.0e-12))

        out["CV_PN_%s" % label] = cv
        cvs.append(cv)

    out["CV_PN_PHASE_MEAN"] = float(np.mean(cvs)) if cvs else 0.0
    return out


def candidate_overcoverage_penalty(old_pn: pd.Series,
                                   candidate_pn: pd.Series,
                                   cfg: Config) -> float:
    """Penalize additions to states that were already overrepresented.

    For each phase, the old cumulative phase mean is used as the reference.
    States above (1 + tolerance) * phase_mean carry a surplus factor.
    Candidate elements added to those states contribute to the penalty.

    The result is normalized by the total candidate element count and is therefore
    comparable across candidates.
    """
    penalty_sum = 0.0
    candidate_total = float(candidate_pn.sum())

    if candidate_total <= 0.0:
        return 0.0

    tol = float(cfg.OVERCOVER_REL_TOL)

    for phase in [cfg.BCC_PHASE_ID, cfg.HCP_PHASE_ID]:
        old_sub = old_pn.loc[phase].astype(float)
        cand_sub = candidate_pn.loc[phase].astype(float)

        phase_mean = float(old_sub.mean())
        if phase_mean <= 0.0:
            # No previous information yet: do not penalize the first RVE.
            continue

        threshold = (1.0 + tol) * phase_mean

        for nd in old_sub.index:
            old_count = float(old_sub.loc[nd])
            added = float(cand_sub.loc[nd])

            if old_count <= threshold or added <= 0.0:
                continue

            # Relative surplus over the phase mean.
            surplus_ratio = (old_count - threshold) / (phase_mean + 1.0e-12)
            penalty_sum += added * surplus_ratio

    return float(penalty_sum / candidate_total)


def score_candidate(candidate_counts: Dict,
                    new_metrics: Dict[str, float],
                    old_counts: Dict,
                    old_metrics: Dict[str, float],
                    accepted_pn_vectors: List[np.ndarray],
                    cfg: Config) -> Tuple[float, Dict[str, float]]:
    d_cpn = new_metrics["C_PN"] - old_metrics.get("C_PN", 0.0)
    d_cpo = new_metrics["C_PO"] - old_metrics.get("C_PO", 0.0)
    d_rge4 = new_metrics.get("R_ge_4", 0.0) - old_metrics.get("R_ge_4", 0.0)

    old_pn = old_counts["PN"]
    cand_pn = candidate_counts["PN"]
    new_pn = old_pn.add(cand_pn, fill_value=0)

    # --------------------------------------------------------
    # A. Hard existence gain
    # --------------------------------------------------------
    old_zero = int((old_pn < int(cfg.EXISTENCE_MIN_COUNT)).sum())
    new_zero = int((new_pn < int(cfg.EXISTENCE_MIN_COUNT)).sum())
    newly_filled_states = int(old_zero - new_zero)

    # --------------------------------------------------------
    # B. Deficit reduction toward N_MIN_PHASE_NDIFF
    # --------------------------------------------------------
    old_deficit = float(
        sum(
            max(0.0, float(cfg.N_MIN_PHASE_NDIFF) - float(c))
            for c in old_pn.values
        )
    )
    new_deficit = float(
        sum(
            max(0.0, float(cfg.N_MIN_PHASE_NDIFF) - float(c))
            for c in new_pn.values
        )
    )

    deficit_reduction = old_deficit - new_deficit
    deficit_norm = float(
        len(old_pn) * max(1, int(cfg.N_MIN_PHASE_NDIFF))
    )
    deficit_reduction_fraction = deficit_reduction / deficit_norm

    # --------------------------------------------------------
    # C. Phase-wise raw-distribution balancing
    # --------------------------------------------------------
    old_balance = phasewise_pn_balance_cv(old_pn, cfg)
    new_balance = phasewise_pn_balance_cv(new_pn, cfg)

    old_balance_cv = float(old_balance["CV_PN_PHASE_MEAN"])
    new_balance_cv = float(new_balance["CV_PN_PHASE_MEAN"])

    # Positive is good.
    balance_improvement = old_balance_cv - new_balance_cv

    # Explicitly punish a candidate for adding many samples to states that were
    # already above the mean of their own phase.
    overcoverage_penalty = candidate_overcoverage_penalty(
        old_pn=old_pn,
        candidate_pn=cand_pn,
        cfg=cfg,
    )

    # --------------------------------------------------------
    # D. Existing coverage / diversity terms
    # --------------------------------------------------------
    m_gain = marginal_pn_gain(old_pn, cand_pn, cfg)

    cand_vec = pn_distribution_vector(cand_pn)
    sim_penalty = 0.0

    if accepted_pn_vectors:
        sim_penalty = max(
            cosine_similarity(cand_vec, v)
            for v in accepted_pn_vectors
        )

    score = (
        cfg.SCORE_W_NEW_STATE_FILL * float(newly_filled_states)
        + cfg.SCORE_W_PRIORITY_REPAIR * float(deficit_reduction_fraction)
        + cfg.SCORE_W_BALANCE_IMPROVEMENT * float(balance_improvement)
        + cfg.SCORE_W_CPN * d_cpn
        + cfg.SCORE_W_CPO * d_cpo
        + cfg.SCORE_W_RGE4 * d_rge4
        + cfg.SCORE_W_MARGINAL_PN * m_gain
        - cfg.SCORE_W_OVERCOVERAGE_PENALTY * float(overcoverage_penalty)
        - cfg.SCORE_W_SIMILARITY_PENALTY * sim_penalty
    )

    detail = {
        "d_C_PN": d_cpn,
        "d_C_PO": d_cpo,
        "d_R_ge_4": d_rge4,

        "newly_filled_PN_states": newly_filled_states,

        "PN_deficit_reduction": deficit_reduction,
        "PN_deficit_reduction_fraction": deficit_reduction_fraction,

        "old_phase_mean_CV": old_balance_cv,
        "new_phase_mean_CV": new_balance_cv,
        "phase_balance_improvement": balance_improvement,

        "overcoverage_penalty": overcoverage_penalty,

        "marginal_PN_gain": m_gain,
        "similarity_penalty": sim_penalty,
    }

    return float(score), detail

def build_one_candidate(rve_id: int,
                        neighbor_df: pd.DataFrame,
                        neighbor_lists: List[List[int]],
                        elem_id_to_pos: Dict[int, int],
                        current_counts: Dict,
                        current_metrics: Dict[str, float],
                        bcc_pool: pd.DataFrame,
                        hcp_pool: pd.DataFrame,
                        accepted_pn_vectors: List[np.ndarray],
                        cfg: Config,
                        rng: np.random.Generator,
                        candidate_no: int,
                        priority_stage: str = "none",
                        priority_targets: Optional[List[Tuple[int, int, int]]] = None
                        ) -> Tuple[pd.DataFrame, Dict, float, Dict]:

    priority_targets = list(priority_targets or [])

    if priority_targets:
        phase_grid, gen_info = generate_priority_repair_phase_field(
            cfg=cfg,
            rng=rng,
            stage=priority_stage,
            targets=priority_targets,
        )
    else:
        family = str(rng.choice(cfg.FAMILY_NAMES))
        phase_grid, gen_info = generate_candidate_phase_field(cfg, rng, family)

    phases = phase_grid_to_element_phase(neighbor_df, phase_grid)
    ndiff = compute_n_diff(phases, neighbor_lists, elem_id_to_pos)

    base_df = candidate_to_base_df(
        rve_id, neighbor_df, phase_grid, ndiff, cfg, gen_info
    )
    assigned_df = assign_orientations_stratified(
        base_df, current_counts, bcc_pool, hcp_pool, cfg, rng
    )

    cand_counts = counts_from_rve(
        assigned_df, cfg, bcc_pool, hcp_pool
    )
    new_counts = add_counts(current_counts, cand_counts)
    new_metrics = compute_metrics(new_counts, cfg)

    score, detail = score_candidate(
        cand_counts,
        new_metrics,
        current_counts,
        current_metrics,
        accepted_pn_vectors,
        cfg,
    )

    # Explicitly score how well this candidate serves the requested deficit states.
    if priority_targets:
        priority_gain = 0.0
        target_added = {}

        for phase, nd, need in priority_targets:
            added = float(cand_counts["PN"].loc[(int(phase), int(nd))])
            key = "%s_N%02d" % (phase_label(int(phase), cfg), int(nd))
            target_added[key] = added

            if priority_stage == "existence":
                # One existing center is enough to satisfy the hard existence target.
                priority_gain += 1.0 if added > 0 else 0.0
            else:
                priority_gain += min(added, max(float(need), 1.0)) / max(float(need), 1.0)

        repair_bonus = float(cfg.SCORE_W_PRIORITY_REPAIR) * float(priority_gain)
        score += repair_bonus

        detail["priority_repair_active"] = True
        detail["priority_stage"] = priority_stage
        detail["priority_target_count"] = len(priority_targets)
        detail["priority_target_added"] = target_added
        detail["priority_repair_gain"] = priority_gain
        detail["priority_repair_bonus"] = repair_bonus
    else:
        detail["priority_repair_active"] = False
        detail["priority_stage"] = "none"
        detail["priority_target_count"] = 0

    shape_pen = shape_penalty_from_df(assigned_df, cfg)
    score -= cfg.SCORE_W_SHAPE_PENALTY * shape_pen

    detail["shape_penalty"] = shape_pen
    detail["candidate_no"] = candidate_no
    detail["family"] = gen_info.get("family", "UNKNOWN")
    detail["hcp_fraction_actual"] = float(
        (phase_grid == cfg.HCP_PHASE_ID).sum()
    ) / float(phase_grid.size)
    detail["score"] = score
    detail.update({"new_" + k: v for k, v in new_metrics.items()})

    assigned_df["Candidate_Score"] = score
    return assigned_df, cand_counts, score, detail


def build_one_candidate_worker(args):
    """Multiprocessing wrapper for candidate evaluation.

    Each worker receives an independent random seed so candidate generation is
    reproducible and independent across CPU processes. This function is defined
    at module level to be picklable on Windows.
    """
    (rve_id, neighbor_df, neighbor_lists, elem_id_to_pos, current_counts,
     current_metrics, bcc_pool, hcp_pool, accepted_pn_vectors, cfg, seed,
     candidate_no, priority_stage, priority_targets) = args
    worker_rng = np.random.default_rng(int(seed))
    return build_one_candidate(
        rve_id=rve_id,
        neighbor_df=neighbor_df,
        neighbor_lists=neighbor_lists,
        elem_id_to_pos=elem_id_to_pos,
        current_counts=current_counts,
        current_metrics=current_metrics,
        bcc_pool=bcc_pool,
        hcp_pool=hcp_pool,
        accepted_pn_vectors=accepted_pn_vectors,
        cfg=cfg,
        rng=worker_rng,
        candidate_no=candidate_no,
        priority_stage=priority_stage,
        priority_targets=priority_targets,
    )


def evaluate_candidate_pool(rve_id: int,
                            neighbor_df: pd.DataFrame,
                            neighbor_lists: List[List[int]],
                            elem_id_to_pos: Dict[int, int],
                            current_counts: Dict,
                            current_metrics: Dict[str, float],
                            bcc_pool: pd.DataFrame,
                            hcp_pool: pd.DataFrame,
                            accepted_pn_vectors: List[np.ndarray],
                            cfg: Config,
                            rng: np.random.Generator) -> Tuple[Tuple[pd.DataFrame, Dict, Dict], List[Dict]]:
    """Evaluate candidate RVEs either serially or in parallel.

    Returns
    -------
    best : (candidate_df, candidate_counts, selected_detail)
    round_details : list of detail dictionaries for all candidates
    """
    n_candidates = int(cfg.CANDIDATES_PER_ROUND)
    n_workers = int(max(1, cfg.N_CPU_WORKERS))
    n_workers = min(n_workers, n_candidates, os.cpu_count() or 1)

    priority_stage, priority_targets = get_priority_pn_targets(
        current_counts, cfg, rve_id
    )

    if priority_targets:
        print(
            "Coverage-driven repair active: stage=%s, target states=%d"
            % (priority_stage, len(priority_targets))
        )
        preview = priority_targets[:12]
        print("  priority preview:", [
            "%s-N%d(need=%d)" % (phase_label(p, cfg), nd, need)
            for p, nd, need in preview
        ])
        if len(priority_targets) > len(preview):
            print("  ... plus %d more target states" % (len(priority_targets) - len(preview)))

    seeds = rng.integers(
        0, np.iinfo(np.uint32).max,
        size=n_candidates, dtype=np.uint32
    )

    tasks = [
        (
            rve_id, neighbor_df, neighbor_lists, elem_id_to_pos,
            current_counts, current_metrics,
            bcc_pool, hcp_pool, accepted_pn_vectors, cfg,
            int(seeds[c - 1]), c,
            priority_stage, priority_targets
        )
        for c in range(1, n_candidates + 1)
    ]

    best = None
    best_score = -1.0e100
    round_details: List[Dict] = []

    if n_workers <= 1:
        for task in tasks:
            cand_df, cand_counts, score, detail = build_one_candidate_worker(task)
            detail["Round_K"] = rve_id
            round_details.append(detail)
            if score > best_score:
                best_score = score
                best = (cand_df, cand_counts, detail)
    else:
        print("Evaluating %d candidates with %d CPU workers ..." % (n_candidates, n_workers))
        with ProcessPoolExecutor(max_workers=n_workers) as executor:
            futures = [executor.submit(build_one_candidate_worker, task) for task in tasks]
            done_count = 0
            for fut in as_completed(futures):
                cand_df, cand_counts, score, detail = fut.result()
                detail["Round_K"] = rve_id
                round_details.append(detail)
                done_count += 1
                if score > best_score:
                    best_score = score
                    best = (cand_df, cand_counts, detail)
                if done_count == n_candidates or done_count % max(1, n_candidates // 4) == 0:
                    print("  candidates finished: %d/%d" % (done_count, n_candidates))

    if best is None:
        raise RuntimeError("No candidate was generated in round %d." % rve_id)
    return best, round_details


# =============================================================================
# Saving, plotting, and reporting
# =============================================================================

def update_sample_weights(all_rve_dfs: List[pd.DataFrame], global_counts: Dict, cfg: Config) -> List[pd.DataFrame]:
    state_weights = compute_state_weights_from_pn(global_counts["PN"], cfg)
    out = []
    for df in all_rve_dfs:
        d = df.copy()
        d["Sample_Weight"] = [float(state_weights.loc[(int(p), int(n))]) for p, n in zip(d["Phase"], d["N_diff"])]
        out.append(d)
    return out


def save_rve_folder(df: pd.DataFrame, rve_index: int, out_root: Path, metrics: Dict, detail: Dict) -> None:
    folder = out_root / ("RVE_%03d" % rve_index)
    ensure_dir(folder)
    df.to_csv(folder / "rve_master.csv", index=False)
    df[["RVE_ID", "Element_ID", "i", "j", "k", "Phase", "N_total", "N_diff", "Eta", "Ndiff_Group"]].to_csv(
        folder / "phase_topology.csv", index=False
    )
    df[["RVE_ID", "Element_ID", "Phase", "N_diff", "Ndiff_Group", "Orientation_ID", "phi1", "Phi", "phi2", "Sample_Weight"]].to_csv(
        folder / "inp_injection_table.csv", index=False
    )
    df.groupby(["Phase", "N_diff"]).size().reset_index(name="Count").to_csv(folder / "phase_ndiff_counts.csv", index=False)
    info = {
        "RVE_Index": rve_index,
        "Metrics_after_acceptance": metrics,
        "Candidate_detail": detail,
        "Columns_for_later_inp_injection": [
            "Element_ID", "Phase", "N_total", "N_diff", "Eta", "Orientation_ID", "phi1", "Phi", "phi2", "Sample_Weight"
        ],
        "Note": "This folder does not contain an Abaqus INP. It contains element-level information to be injected into a 20^3 template INP later."
    }
    with open(folder / "rve_info.json", "w", encoding="utf-8") as f:
        json.dump(info, f, indent=2, ensure_ascii=False)


def save_global_outputs(out_root: Path, all_rve_dfs: List[pd.DataFrame], global_counts: Dict,
                        history: List[Dict], candidate_details: List[Dict], cfg: Config) -> None:
    if all_rve_dfs:
        pd.concat(all_rve_dfs, ignore_index=True).to_csv(out_root / "RVE_all_master_current.csv", index=False)
    pd.DataFrame(history).to_csv(out_root / "coverage_history.csv", index=False)
    pd.DataFrame(candidate_details).to_csv(out_root / "candidate_scores_all_rounds.csv", index=False)
    global_counts["PN"].reset_index(name="Count").to_csv(out_root / "cumulative_phase_ndiff_counts.csv", index=False)
    global_counts["PO"].reset_index(name="Count").to_csv(out_root / "cumulative_phase_orientation_counts.csv", index=False)
    global_counts["POG"].reset_index(name="Count").to_csv(out_root / "cumulative_orientation_ndiff_group_counts.csv", index=False)

    # Extra diagnostics for later publication-style plots:
    # before/after weighting balance and orientation distribution checks.
    raw_w, used_w = compute_state_weights_raw_and_used(global_counts["PN"], cfg)
    diag = global_counts["PN"].reset_index(name="Count")
    diag["Weight_Raw"] = [
        float(raw_w.loc[(int(p), int(n))])
        if pd.notna(raw_w.loc[(int(p), int(n))]) else np.nan
        for p, n in zip(diag["Phase"], diag["N_diff"])
    ]
    diag["Weight_Used"] = [
        float(used_w.loc[(int(p), int(n))])
        if pd.notna(used_w.loc[(int(p), int(n))]) else np.nan
        for p, n in zip(diag["Phase"], diag["N_diff"])
    ]
    # Backward-compatible column name for old plotting scripts.
    diag["Weight_Capped"] = diag["Weight_Used"]
    diag["Effective_Covered"] = diag["Count"] >= cfg.N_MIN_PHASE_NDIFF
    diag["Undercovered"] = diag["Count"] < cfg.N_MIN_PHASE_NDIFF
    diag.to_csv(out_root / "cumulative_phase_ndiff_weight_diagnostics.csv", index=False)

    present = (global_counts["POG"] >= cfg.G_MIN_ORI_GROUP).astype(int)
    group_counts = present.groupby(level=["Phase", "Orientation_ID"]).sum().reset_index(name="Covered_Group_Count")
    group_counts.to_csv(out_root / "cumulative_orientation_group_coverage_summary.csv", index=False)


def plot_dashboard(history: List[Dict], out_root: Path, cfg: Config) -> None:
    if not history:
        return
    h = pd.DataFrame(history)
    fig, axes = plt.subplots(2, 2, figsize=(10.5, 7.2), dpi=150)
    ax = axes[0, 0]
    ax.plot(h["K"], h["C_PN"], marker="o")
    ax.set_xlabel("Number of accumulated basis RVEs, K")
    ax.set_ylabel(r"$C_{PN}$")
    ax.set_title(r"Phase-$N_{diff}$ coverage")
    ax.grid(True, linestyle="--", alpha=0.4)

    ax = axes[0, 1]
    ax.plot(h["K"], h["C_PO"], marker="o")
    ax.set_xlabel("Number of accumulated basis RVEs, K")
    ax.set_ylabel(r"$C_{PO}$")
    ax.set_title("Phase-Orientation coverage")
    ax.grid(True, linestyle="--", alpha=0.4)

    ax = axes[1, 0]
    ax.plot(h["K"], h["R_ge_4"], marker="o")
    ax.set_xlabel("Number of accumulated basis RVEs, K")
    ax.set_ylabel(r"$R_{\geq 4}$")
    ax.set_title(r"Orientation-$N_{diff}$ group decoupling")
    ax.grid(True, linestyle="--", alpha=0.4)

    ax = axes[1, 1]
    ax.plot(h["K"], h["N_undercovered"], marker="o")
    ax.set_xlabel("Number of accumulated basis RVEs, K")
    ax.set_ylabel("Undercovered Phase-Ndiff states")
    ax.set_title("Remaining undercovered states")
    ax.grid(True, linestyle="--", alpha=0.4)

    fig.suptitle("Coverage convergence of adaptive basis-RVE construction", y=1.02)
    fig.tight_layout()
    fig.savefig(out_root / "coverage_dashboard_current.png", bbox_inches="tight")
    if cfg.SAVE_DASHBOARD_EACH_ROUND:
        fig.savefig(out_root / ("coverage_dashboard_K%03d.png" % int(h["K"].iloc[-1])), bbox_inches="tight")
    if cfg.SHOW_DASHBOARD:
        plt.show()
    plt.close(fig)

def stop_criteria_check(history: List[Dict], cfg: Config) -> Dict[str, bool]:
    if len(history) < 2:
        return {"CPN": False, "CPO": False, "RGE4": False, "UNDER": False, "ALL": False}
    last = history[-1]
    prev = history[-2]
    d_cpn = last["C_PN"] - prev["C_PN"]
    d_cpo = last["C_PO"] - prev["C_PO"]
    d_rge4 = last["R_ge_4"] - prev["R_ge_4"]
    under_reduction = int(prev["N_undercovered"] - last["N_undercovered"])
    flags = {
        "CPN": d_cpn < cfg.STOP_DCPN,
        "CPO": d_cpo < cfg.STOP_DCPO,
        "RGE4": d_rge4 < cfg.STOP_DRGE4,
        "UNDER": under_reduction <= cfg.STOP_DUNDERCOVERED_REDUCTION_MAX,
    }
    flags["ALL"] = all(flags.values())
    return flags


def print_round_summary(k: int, selected_detail: Dict, metrics: Dict, history: List[Dict], cfg: Config) -> None:
    print("\n" + "=" * 72)
    print("Accepted RVE #%d" % k)
    print("Generator type   : %s" % selected_detail.get("family", "UNKNOWN"))
    print("Candidate score  : %.6f" % float(selected_detail.get("score", 0.0)))
    print("Priority stage   : %s" % selected_detail.get("priority_stage", "none"))
    print("Balance gain     : %.6f" % float(selected_detail.get("phase_balance_improvement", 0.0)))
    print("Overcoverage pen.: %.6f" % float(selected_detail.get("overcoverage_penalty", 0.0)))
    print("\nMain convergence metrics:")
    print("  C_PN            = %.6f" % metrics["C_PN"])
    print("  C_PO            = %.6f" % metrics["C_PO"])
    print("  R_>=4           = %.6f" % metrics.get("R_ge_4", 0.0))
    print("  N_undercovered  = %d" % int(metrics.get("N_undercovered", 0)))

    print("\nAuxiliary orientation-group diagnostics:")
    for n in range(2, len(cfg.NDIFF_GROUPS) + 1):
        print("  R_>=%d           = %.6f" % (n, metrics.get("R_ge_%d" % n, 0.0)))
    print("  Mean group count = %.6f" % metrics.get("Mean_Group_Count", 0.0))

    print("\nWeight / existence diagnostics:")
    print("  W95_used        = %.6f" % metrics.get("W95_used", metrics.get("W95", float("nan"))))
    print("  W95_raw         = %.6f" % metrics.get("W95_raw", float("nan")))
    print("  Wmax_used       = %.6f" % metrics.get("Wmax_used", metrics.get("Wmax_raw", float("nan"))))
    print("  Weight cap on?  = %s" % ("YES" if cfg.USE_WEIGHT_CAP else "NO"))
    print("  Zero PN states  = %d" % int(metrics.get("Zero_PN_states", 0)))
    print("  PN total deficit= %d" % int(metrics.get("PN_total_deficit", 0)))
    print("  CV_PN_BCC       = %.6f" % metrics.get("CV_PN_BCC", float("nan")))
    print("  CV_PN_HCP       = %.6f" % metrics.get("CV_PN_HCP", float("nan")))
    print("  CV phase mean   = %.6f" % metrics.get("CV_PN_PHASE_MEAN", float("nan")))

    if len(history) >= 2:
        last = history[-1]
        prev = history[-2]
        d_cpn = last["C_PN"] - prev["C_PN"]
        d_cpo = last["C_PO"] - prev["C_PO"]
        d_r = last["R_ge_4"] - prev["R_ge_4"]
        under_reduction = int(prev["N_undercovered"] - last["N_undercovered"])
        print("\nIncrement from previous step:")
        print("  ΔC_PN                 = %+ .6f" % d_cpn)
        print("  ΔC_PO                 = %+ .6f" % d_cpo)
        print("  ΔR_>=4                = %+ .6f" % d_r)
        print("  N_undercovered change = %d -> %d  (reduction = %d)" % (
            int(prev["N_undercovered"]), int(last["N_undercovered"]), under_reduction))

        flags = stop_criteria_check(history, cfg)
        print("\nStop criteria check:")
        print("  C_PN improvement < %.2f%% ?                %s" % (cfg.STOP_DCPN * 100, "YES" if flags["CPN"] else "NO"))
        print("  C_PO improvement < %.2f%% ?                %s" % (cfg.STOP_DCPO * 100, "YES" if flags["CPO"] else "NO"))
        print("  R_>=4 improvement < %.2f%% ?               %s" % (cfg.STOP_DRGE4 * 100, "YES" if flags["RGE4"] else "NO"))
        print("  N_undercovered reduction <= %d state(s)?  %s" % (cfg.STOP_DUNDERCOVERED_REDUCTION_MAX, "YES" if flags["UNDER"] else "NO"))
        print("  All criteria met?                         %s" % ("YES" if flags["ALL"] else "NO"))
    else:
        print("\nStop criteria check:")
        print("  Not available after the first RVE. At least two accepted RVEs are needed.")
    print("=" * 72 + "\n")

def ask_continue(cfg: Config, all_met: bool) -> str:
    if cfg.AUTO_STOP_ENABLED and all_met:
        return "n"
    if not cfg.INTERACTIVE_MODE:
        return "y"
    while True:
        ans = input("Continue adding one more RVE? [y] continue / [n] stop / [a] auto mode: ").strip().lower()
        if ans in ("y", "n", "a"):
            return ans
        print("Please input y, n, or a.")


# =============================================================================
# Main adaptive loop
# =============================================================================

def main(cfg: Config = CFG) -> None:
    random.seed(cfg.RANDOM_SEED)
    rng = np.random.default_rng(cfg.RANDOM_SEED)

    out_root = Path(cfg.OUTPUT_ROOT)
    if cfg.CLEAR_OUTPUT_ROOT_ON_START and out_root.exists():
        shutil.rmtree(out_root)
    ensure_dir(out_root)

    print("Reading periodic neighbor map:", cfg.NEIGHBOR_MAP_CSV)
    neighbor_df = load_neighbor_map(cfg.NEIGHBOR_MAP_CSV)
    n_elem = len(neighbor_df)
    expected = cfg.NX * cfg.NY * cfg.NZ
    if n_elem != expected:
        print("WARNING: neighbor map has %d elements, but NX*NY*NZ = %d" % (n_elem, expected))

    neighbor_lists = neighbor_df["Neighbor_List"].tolist()
    elem_id_to_pos = {int(eid): pos for pos, eid in enumerate(neighbor_df["Element_ID"].tolist())}

    bcc_pool = load_orientation_pool(cfg.BCC_ORIENTATION_POOL_CSV, "BCC", cfg.DUMMY_BCC_ORIENTATION_COUNT, cfg.ALLOW_DUMMY_ORIENTATION_POOL)
    hcp_pool = load_orientation_pool(cfg.HCP_ORIENTATION_POOL_CSV, "HCP", cfg.DUMMY_HCP_ORIENTATION_COUNT, cfg.ALLOW_DUMMY_ORIENTATION_POOL)

    if bcc_pool[["phi1", "Phi", "phi2"]].isna().any().any() or hcp_pool[["phi1", "Phi", "phi2"]].isna().any().any():
        print("WARNING: Dummy or incomplete orientation pool detected. This is OK for workflow testing, but NOT for final INP injection.")

    # Save config snapshot
    with open(out_root / "builder_config_snapshot.json", "w", encoding="utf-8") as f:
        json.dump(cfg.__dict__, f, indent=2, ensure_ascii=False)

    global_counts = empty_counts(cfg, bcc_pool, hcp_pool)
    current_metrics = compute_metrics(global_counts, cfg)
    all_rve_dfs: List[pd.DataFrame] = []
    accepted_details: List[Dict] = []
    accepted_pn_vectors: List[np.ndarray] = []
    history: List[Dict] = []
    all_candidate_details: List[Dict] = []

    auto_mode = not cfg.INTERACTIVE_MODE

    for k in range(1, cfg.MAX_RVE_COUNT + 1):
        print("\nGenerating candidate pool for RVE #%d ..." % k)
        best, round_details = evaluate_candidate_pool(
            rve_id=k,
            neighbor_df=neighbor_df,
            neighbor_lists=neighbor_lists,
            elem_id_to_pos=elem_id_to_pos,
            current_counts=global_counts,
            current_metrics=current_metrics,
            bcc_pool=bcc_pool,
            hcp_pool=hcp_pool,
            accepted_pn_vectors=accepted_pn_vectors,
            cfg=cfg,
            rng=rng,
        )
        selected_df, selected_counts, selected_detail = best

        # Accept the best candidate
        global_counts = add_counts(global_counts, selected_counts)
        current_metrics = compute_metrics(global_counts, cfg)
        all_rve_dfs.append(selected_df)
        accepted_details.append(dict(selected_detail))
        accepted_pn_vectors.append(pn_distribution_vector(selected_counts["PN"]))

        # Update sample weights globally and refresh previously saved RVE files as well.
        all_rve_dfs = update_sample_weights(all_rve_dfs, global_counts, cfg)
        selected_df = all_rve_dfs[-1]

        # Save outputs
        save_rve_folder(selected_df, k, out_root, current_metrics, selected_detail)
        all_candidate_details.extend(round_details)

        hist_row = {
            "K": k,
            "Selected_Family": selected_detail.get("family", "UNKNOWN"),
            "Selected_Score": float(selected_detail.get("score", 0.0)),
            "C_PN": current_metrics["C_PN"],
            "C_PO": current_metrics["C_PO"],
            "R_ge_2": current_metrics.get("R_ge_2", 0.0),
            "R_ge_3": current_metrics.get("R_ge_3", 0.0),
            "R_ge_4": current_metrics.get("R_ge_4", 0.0),
            "R_ge_5": current_metrics.get("R_ge_5", 0.0),
            "R_ge_6": current_metrics.get("R_ge_6", 0.0),
            "R_3": current_metrics.get("R_ge_3", 0.0),
            "Mean_Group_Count": current_metrics.get("Mean_Group_Count", 0.0),
            "N_undercovered": current_metrics["N_undercovered"],
            "N_effectively_covered": current_metrics["N_effectively_covered"],
            "Zero_PN_states": current_metrics["Zero_PN_states"],
            "W95": current_metrics["W95"],
            "W95_capped": current_metrics["W95_capped"],
            "Wmax_capped": current_metrics["Wmax_capped"],
            "W95_raw": current_metrics["W95_raw"],
            "Wmax_raw": current_metrics["Wmax_raw"],
            "Cap_hit_states": current_metrics["Cap_hit_states"],
            "Cap_hit_ratio": current_metrics["Cap_hit_ratio"],
            "CV_PN": current_metrics["CV_PN"],
            "CV_PN_BCC": current_metrics.get("CV_PN_BCC", np.nan),
            "CV_PN_HCP": current_metrics.get("CV_PN_HCP", np.nan),
            "CV_PN_PHASE_MEAN": current_metrics.get("CV_PN_PHASE_MEAN", np.nan),
            "PN_total_deficit": current_metrics.get("PN_total_deficit", 0),
        }
        if history:
            prev = history[-1]
            hist_row["dC_PN"] = hist_row["C_PN"] - prev["C_PN"]
            hist_row["dC_PO"] = hist_row["C_PO"] - prev["C_PO"]
            hist_row["dR_ge_4"] = hist_row["R_ge_4"] - prev["R_ge_4"]
            hist_row["dN_undercovered_reduction"] = int(prev["N_undercovered"] - hist_row["N_undercovered"])
        else:
            hist_row["dC_PN"] = np.nan
            hist_row["dC_PO"] = np.nan
            hist_row["dR_ge_4"] = np.nan
            hist_row["dN_undercovered_reduction"] = np.nan
        history.append(hist_row)

        # Refresh all RVE folders with updated Sample_Weight, while preserving
        # each RVE's original candidate detail in rve_info.json.
        for idx, d in enumerate(all_rve_dfs, start=1):
            detail_to_save = dict(accepted_details[idx - 1])
            detail_to_save["weight_refresh_after_K"] = k
            save_rve_folder(d, idx, out_root, current_metrics, detail_to_save)

        save_global_outputs(out_root, all_rve_dfs, global_counts, history, all_candidate_details, cfg)
        plot_dashboard(history, out_root, cfg)
        print_round_summary(k, selected_detail, current_metrics, history, cfg)

        flags = stop_criteria_check(history, cfg)

        full_existence = int(current_metrics.get("Zero_PN_states", 0)) == 0

        if auto_mode or cfg.AUTO_STOP_ENABLED:
            if (
                flags.get("ALL", False)
                and k >= 2
                and (
                    full_existence
                    or not cfg.REQUIRE_FULL_PN_EXISTENCE_BEFORE_STOP
                )
            ):
                print("Auto-stop: all stop criteria are met and full Phase-Ndiff existence is satisfied.")
                break
            continue

        ans = ask_continue(cfg, flags.get("ALL", False))

        if ans == "n":
            if (
                cfg.REQUIRE_FULL_PN_EXISTENCE_BEFORE_STOP
                and not full_existence
            ):
                print(
                    "Cannot stop yet: %d Phase-Ndiff state(s) are still absent. "
                    "The next RVE will prioritize them."
                    % int(current_metrics.get("Zero_PN_states", 0))
                )
                continue

            print("Stopped by user.")
            break
        if ans == "a":
            print("Switching to auto mode. The script will continue until stop criteria or MAX_RVE_COUNT.")
            auto_mode = True

    final_zero_states = int(current_metrics.get("Zero_PN_states", 0))
    if cfg.REQUIRE_FULL_PN_EXISTENCE_BEFORE_STOP and final_zero_states > 0:
        raise RuntimeError(
            "MAX_RVE_COUNT reached but %d Phase-Ndiff state(s) are still absent. "
            "Increase MAX_RVE_COUNT or candidate count." % final_zero_states
        )

    print("\nAdaptive basis-RVE construction finished.")
    print("Output root:", str(out_root))
    print("Use RVE_XXX/inp_injection_table.csv or RVE_all_master_current.csv for later INP injection.")


if __name__ == "__main__":
    main(CFG)
