# -*- coding: utf-8 -*-
"""
04_inject_rve_info_to_inp_with_4loadgroups_strict.py

Purpose
-------
Step-04 for the CPFE basis-RVE workflow.

This script does TWO things in one pass:

1) Case control / working-condition update
   It updates each INP template according to the CASES table:
       - temperature in *Initial Conditions, type=TEMPERATURE
       - complete AMP-1 time-amplitude history
       - *Static increment line
       - *Output field/history time interval
       - target boundary data line under *Boundary, amplitude=AMP-1

2) RVE injection
   It injects each RVE_K/inp_injection_table.csv generated by Step-03 into
   every case INP and writes:
       OUTPUT_ROOT/RVE_001/01_001_20.inp
       OUTPUT_ROOT/RVE_001/02_001_500.inp
       ...

What this script changes
------------------------
- Case settings: temperature, amplitude end time, static line, output interval,
  target boundary condition data line.
- RVE microstructure blocks: GRAIN-* elsets, PHASE-* elsets, *Solid Section,
  *Material/*User Material constants.

What this script preserves
--------------------------
- Nodes and elements.
- Assembly / instance / PBC equations.
- Other boundary conditions and output requests, except the time interval lines
  configured by CASES.

Recommended usage
-----------------
Run with normal Python, not Abaqus Python:
    python 04_inject_rve_info_to_inp_with_4loadgroups_strict.py

Notes
-----
- CASES uses the same idea as your previous 01_001_20 -> 9-case generator.
- static_line controls Abaqus internal increment size.
- output_interval controls how often Abaqus writes field/history output.
- boundary_line controls the exact data line under *Boundary, amplitude=AMP-1,
  for example: PBC_REFMACRO3, 3, 3, 0.162.
  These controls can be different. For example, use smaller static increments
  for convergence while keeping output_interval unchanged.
"""
from __future__ import annotations

import csv
import json
import math
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


# =============================================================================
# 0. CONFIGURATION AREA
# =============================================================================

@dataclass(frozen=True)
class CaseItem:
    case_id: str
    rate_tag: str
    temp_tag: str
    temperature: str
    amplitude_points: Tuple[Tuple[str, str], ...]
    static_line: str
    output_interval: str
    boundary_line: str

    @property
    def filename(self) -> str:
        return "%s_%s_%s.inp" % (self.case_id, self.rate_tag, self.temp_tag)

    @property
    def amp_end_time(self) -> str:
        return str(self.amplitude_points[-1][0])


@dataclass
class Config:
    # Folder containing configured template INPs.
    # If GENERATE_CASES_FROM_SINGLE_TEMPLATE=False, the script reads one template
    # per CASE from this folder, e.g. 01_001_20.inp, 02_001_500.inp, ...
    INPUT_INP_DIR: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\04_inject_rve_info_to_inp_file\input"

    # Optional single base template.
    # If GENERATE_CASES_FROM_SINGLE_TEMPLATE=True, all cases are generated in
    # memory from this one template before RVE injection.
    BASE_TEMPLATE_INP: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\04_inject_rve_info_to_inp_file\input\01_001_20.inp"

    # Root folder produced by 03_adaptive_basis_rve_builder*.py.
    # It should contain RVE_001/inp_injection_table.csv, RVE_002/..., etc.
    RVE_INFO_ROOT: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\03_adaptive_basis_rve_builder_file"

    # Output folder. The script will create OUTPUT_ROOT/RVE_001/, OUTPUT_ROOT/RVE_002/, ...
    OUTPUT_ROOT: str = r"F:\1_job\20251124\CPFE_PARAMATER_TEST_PBC\2_RVE_BUILD\04_inject_rve_info_to_inp_file"

    # Select exactly one of:
    #   01_Tension
    #   02_Compression
    #   03_TensionReversal
    #   04_CompressionReversal
    ACTIVE_LOAD_GROUP: str = "04_CompressionReversal"

    # True -> OUTPUT_ROOT/<ACTIVE_LOAD_GROUP>/RVE_001/...
    # False -> OUTPUT_ROOT/RVE_001/... (same layout as the previous 04 script)
    ADD_LOAD_GROUP_SUBDIR: bool = True

    # RVE selection.
    RVE_IDS: Tuple[int, ...] = (1,2,3,4,5,6,7)
    AUTO_DETECT_RVES: bool = False

    # -------------------------------------------------------------------------
    # Case-control switch
    # -------------------------------------------------------------------------
    ENABLE_CASE_CONTROL: bool = True

    # False: read each case template from INPUT_INP_DIR and update it by CASES.
    # True : use BASE_TEMPLATE_INP as the only template and generate all cases
    #        in memory before RVE injection.
    GENERATE_CASES_FROM_SINGLE_TEMPLATE: bool = False

    # If True, all enabled CASES must exist in INPUT_INP_DIR when
    # GENERATE_CASES_FROM_SINGLE_TEMPLATE=False.
    REQUIRE_ALL_CASE_TEMPLATES: bool = True

    # Boundary condition replacement target.
    # The actual replacement line is now configured per CASE through CaseItem.boundary_line.
    # Example boundary_line: "PBC_REFMACRO3, 3, 3, 0.162"
    BOUNDARY_AMPLITUDE_NAME: str = "AMP-1"
    BOUNDARY_TARGET_NAME: str = "PBC_REFMACRO3"

    # Template selection when ENABLE_CASE_CONTROL=False.
    # Empty tuple means all *.inp files in INPUT_INP_DIR.
    TEMPLATE_INP_FILES: Tuple[str, ...] = ()

    # Output behavior.
    CLEAR_OUTPUT_ROOT_ON_START: bool = False
    OVERWRITE_EXISTING_INP: bool = True

    # Abaqus / UMAT convention.
    BCC_PHASE_ID: int = 1
    HCP_PHASE_ID: int = 9
    N_TOTAL_NEIGHBORS: int = 26

    # Material and set naming convention.
    GRAIN_SET_PREFIX: str = "GRAIN-"
    PHASE_SET_PREFIX: str = "PHASE-"
    MATERIAL_PREFIX: str = "MATERIAL-GRAIN"

    # User material constants written to INP:
    #   phi1, Phi, phi2, Element_ID, Phase, Reserved_0, N_total, N_diff, Sample_Weight
    USER_MATERIAL_CONSTANTS: int = 9
    RESERVED_CONSTANT_6: float = 0.0

    # Abaqus data line formatting.
    MAX_VALUES_PER_LINE: int = 8
    ELSET_IDS_PER_LINE: int = 16
    FLOAT_FORMAT: str = "{:.12g}"

    # Preserve the exact material keyword order from the original INP prototype.
    # For the current templates this is:
    #   *Material -> *Depvar -> 120, -> *User Material -> data
    USE_TEMPLATE_MATERIAL_PROTOTYPE: bool = True
    FALLBACK_MINIMAL_MATERIAL: bool = False
    REQUIRE_UNIFORM_TEMPLATE_MATERIAL_STRUCTURE: bool = True
    EXPECTED_DEPVAR_COUNT: int = 120
    VALIDATE_EVERY_GENERATED_MATERIAL: bool = True

    # Replacement strategy: replace from first *Elset, elset=GRAIN- to *End Part.
    REPLACE_FROM_FIRST_GRAIN_TO_END_PART: bool = True

    # Validate that all Element_ID values exist in each template.
    VALIDATE_ELEMENT_IDS: bool = True

    # Write logs and summaries.
    WRITE_SUMMARY_CSV: bool = True
    WRITE_RVE_LOCAL_COPY_OF_INJECTION_TABLE: bool = True
    WRITE_CASE_CONTROL_SUMMARY: bool = True

    # Final safety checks. These checks are intentionally strict because an INP
    # that silently loses the Initial boundary conditions or temperature field
    # can still be submitted by Abaqus but will generate an invalid database.
    STRICT_FINAL_VALIDATION: bool = True
    REQUIRE_ASSEMBLY_EXACTLY_PRESERVED: bool = True
    REQUIRE_ALL_OUTPUT_INTERVALS_EQUAL: bool = True


# =============================================================================
# Four loading groups
# =============================================================================
#
# amplitude_points is the complete AMP-1 history:
#   ((time_0, value_0), (time_1, value_1), ...)
#
# The monotonic groups deliberately use the same two-point amplitude as the
# previous strict 04 script. For these two groups, replace_amplitude() preserves
# the original data-line formatting and only changes the end time, so the new
# output can be compared directly with files generated by the previous script.
#
# Reversal groups:
#   03_TensionReversal:     H33 : 0 -> +0.054 -> 0
#   04_CompressionReversal: H33 : 0 -> -0.054 -> 0
#
# All four groups retain 180 standard intervals:
#   0.01 /s -> total 10.8 s, DTIME/output interval 0.06 s
#   0.1  /s -> total 1.08 s, DTIME/output interval 0.006 s
#   0.6  /s -> total 0.18 s, DTIME/output interval 0.001 s

TENSION_CASES: Tuple[CaseItem, ...] = tuple(CaseItem(*x) for x in [
    ("01", "001", "20",  "293.15",  (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.108"),
    ("02", "001", "500", "773.15",  (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.108"),
    ("05", "001", "800", "1073.15", (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.108"),

    ("06", "01",  "20",  "293.15",  (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.108"),
    ("07", "01",  "500", "773.15",  (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.108"),
    ("10", "01",  "800", "1073.15", (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.108"),

    ("11", "06",  "20",  "293.15",  (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.108"),
    ("12", "06",  "500", "773.15",  (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.108"),
    ("15", "06",  "800", "1073.15", (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.108"),
])

COMPRESSION_CASES: Tuple[CaseItem, ...] = tuple(CaseItem(*x) for x in [
    ("01", "001", "20",  "293.15",  (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.108"),
    ("02", "001", "500", "773.15",  (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.108"),
    ("05", "001", "800", "1073.15", (("0", "0"), ("10.8", "1")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.108"),

    ("06", "01",  "20",  "293.15",  (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.108"),
    ("07", "01",  "500", "773.15",  (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.108"),
    ("10", "01",  "800", "1073.15", (("0", "0"), ("1.08", "1")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.108"),

    ("11", "06",  "20",  "293.15",  (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.108"),
    ("12", "06",  "500", "773.15",  (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.108"),
    ("15", "06",  "800", "1073.15", (("0", "0"), ("0.18", "1")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.108"),
])

TENSION_REVERSAL_CASES: Tuple[CaseItem, ...] = tuple(CaseItem(*x) for x in [
    ("01", "001", "20",  "293.15",  (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.054"),
    ("02", "001", "500", "773.15",  (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.054"),
    ("05", "001", "800", "1073.15", (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, 0.054"),

    ("06", "01",  "20",  "293.15",  (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.054"),
    ("07", "01",  "500", "773.15",  (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.054"),
    ("10", "01",  "800", "1073.15", (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, 0.054"),

    ("11", "06",  "20",  "293.15",  (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.054"),
    ("12", "06",  "500", "773.15",  (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.054"),
    ("15", "06",  "800", "1073.15", (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, 0.054"),
])

COMPRESSION_REVERSAL_CASES: Tuple[CaseItem, ...] = tuple(CaseItem(*x) for x in [
    ("01", "001", "20",  "293.15",  (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.054"),
    ("02", "001", "500", "773.15",  (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.054"),
    ("05", "001", "800", "1073.15", (("0", "0"), ("5.4",  "1"), ("10.8", "0")), "0.06, 10.8, 1e-08, 0.06",    "0.06",  "PBC_REFMACRO3, 3, 3, -0.054"),

    ("06", "01",  "20",  "293.15",  (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.054"),
    ("07", "01",  "500", "773.15",  (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.054"),
    ("10", "01",  "800", "1073.15", (("0", "0"), ("0.54", "1"), ("1.08", "0")), "0.006, 1.08, 1e-08, 0.006",  "0.006", "PBC_REFMACRO3, 3, 3, -0.054"),

    ("11", "06",  "20",  "293.15",  (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.054"),
    ("12", "06",  "500", "773.15",  (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.054"),
    ("15", "06",  "800", "1073.15", (("0", "0"), ("0.09", "1"), ("0.18", "0")), "0.001, 0.18, 1e-08, 0.001",  "0.001", "PBC_REFMACRO3, 3, 3, -0.054"),
])

LOAD_GROUP_CASES: Dict[str, Tuple[CaseItem, ...]] = {
    "01_Tension": TENSION_CASES,
    "02_Compression": COMPRESSION_CASES,
    "03_TensionReversal": TENSION_REVERSAL_CASES,
    "04_CompressionReversal": COMPRESSION_REVERSAL_CASES,
}

CFG = Config()
if CFG.ACTIVE_LOAD_GROUP not in LOAD_GROUP_CASES:
    raise ValueError(
        "Unknown ACTIVE_LOAD_GROUP=%r. Available groups: %s"
        % (CFG.ACTIVE_LOAD_GROUP, sorted(LOAD_GROUP_CASES))
    )
CASES: Tuple[CaseItem, ...] = LOAD_GROUP_CASES[CFG.ACTIVE_LOAD_GROUP]


def validate_active_case_configuration(
    load_group: str,
    cases: Sequence[CaseItem],
) -> None:
    """Validate the four load-group tables before any INP is touched."""
    if len(cases) != 9:
        raise ValueError("%s must contain exactly 9 cases; found %d." % (load_group, len(cases)))

    filenames = [c.filename for c in cases]
    if len(set(filenames)) != len(filenames):
        raise ValueError("Duplicated case filenames in %s." % load_group)

    expected_temperatures = {
        "20": 293.15,
        "500": 773.15,
        "800": 1073.15,
    }
    monotonic = load_group in ("01_Tension", "02_Compression")
    expected_abs_h33 = 0.108 if monotonic else 0.054
    expected_sign = 1.0 if load_group in ("01_Tension", "03_TensionReversal") else -1.0

    for case in cases:
        points = tuple(
            (
                float(str(t).replace("D", "E").replace("d", "e")),
                float(str(a).replace("D", "E").replace("d", "e")),
            )
            for t, a in case.amplitude_points
        )
        if len(points) < 2 or any(points[i][0] <= points[i - 1][0] for i in range(1, len(points))):
            raise ValueError("Amplitude times must be strictly increasing for %s." % case.filename)
        if not np.allclose(points[0], (0.0, 0.0), rtol=0.0, atol=1.0e-14):
            raise ValueError("%s must start from amplitude point (0, 0)." % case.filename)

        static_values = [
            float(x.strip().replace("D", "E").replace("d", "e"))
            for x in case.static_line.split(",")
            if x.strip()
        ]
        if len(static_values) != 4:
            raise ValueError("%s must have four *Static values." % case.filename)

        total_time = points[-1][0]
        output_interval = float(case.output_interval)
        if abs(static_values[1] - total_time) > 1.0e-12:
            raise ValueError(
                "%s: *Static total time=%g differs from amplitude end time=%g."
                % (case.filename, static_values[1], total_time)
            )
        if (
            abs(static_values[0] - output_interval) > 1.0e-14
            or abs(static_values[3] - output_interval) > 1.0e-14
        ):
            raise ValueError(
                "%s: initial/max *Static increments must equal output_interval."
                % case.filename
            )
        n_intervals = total_time / output_interval
        if abs(n_intervals - 180.0) > 1.0e-9:
            raise ValueError(
                "%s: expected 180 standard intervals, obtained %.12g."
                % (case.filename, n_intervals)
            )

        if monotonic:
            expected_points = ((0.0, 0.0), (total_time, 1.0))
        else:
            expected_points = ((0.0, 0.0), (0.5 * total_time, 1.0), (total_time, 0.0))
        if not np.allclose(
            np.asarray(points),
            np.asarray(expected_points),
            rtol=0.0,
            atol=1.0e-12,
        ):
            raise ValueError(
                "%s has unexpected amplitude history: %s; expected %s."
                % (case.filename, points, expected_points)
            )

        parts = [x.strip() for x in case.boundary_line.split(",")]
        if len(parts) != 4:
            raise ValueError("Invalid boundary_line for %s: %s" % (case.filename, case.boundary_line))
        if parts[0].upper() != "PBC_REFMACRO3" or parts[1:3] != ["3", "3"]:
            raise ValueError(
                "%s must control PBC_REFMACRO3 DOF 3 for the current four groups."
                % case.filename
            )
        h33 = float(parts[3])
        if abs(abs(h33) - expected_abs_h33) > 1.0e-12 or math.copysign(1.0, h33) != expected_sign:
            raise ValueError(
                "%s has unexpected H33=%g for load group %s."
                % (case.filename, h33, load_group)
            )

        expected_temp = expected_temperatures.get(case.temp_tag)
        if expected_temp is None or abs(float(case.temperature) - expected_temp) > 1.0e-9:
            raise ValueError(
                "%s has inconsistent temperature tag/value: %s / %s."
                % (case.filename, case.temp_tag, case.temperature)
            )


validate_active_case_configuration(CFG.ACTIVE_LOAD_GROUP, CASES)


# =============================================================================
# 1. Basic helpers
# =============================================================================

NUM = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][-+]?\d+)?"


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_text_lines(path: Path) -> List[str]:
    with open(path, "r", errors="ignore") as f:
        return f.readlines()


def write_text_lines(path: Path, lines: Sequence[str]) -> None:
    ensure_dir(path.parent)
    with open(path, "w", newline="") as f:
        f.writelines(lines)


def split_eol_text(line: str) -> Tuple[str, str]:
    if line.endswith("\r\n"):
        return line[:-2], "\r\n"
    if line.endswith("\n"):
        return line[:-1], "\n"
    if line.endswith("\r"):
        return line[:-1], "\r"
    return line, ""


def is_keyword(line: str) -> bool:
    return line.lstrip().startswith("*")


def keyword_lower(line: str) -> str:
    return line.strip().lower()


def compact_lower(line: str) -> str:
    content, _ = split_eol_text(line)
    return content.lower().replace(" ", "").replace("\t", "")


def parse_keyword_options(line: str) -> Dict[str, str]:
    opts: Dict[str, str] = {}
    parts = line.strip().split(",")
    for token in parts[1:]:
        token = token.strip()
        if "=" in token:
            k, v = token.split("=", 1)
            opts[k.strip().lower()] = v.strip()
    return opts


def format_float(x, fmt: str) -> str:
    try:
        return fmt.format(float(x))
    except Exception:
        return str(x)


def format_abaqus_real(x, fmt: str) -> str:
    """Format every UMAT property as an Abaqus real number.

    Integer-valued properties are intentionally written with a trailing dot
    (for example ``7134.``), matching the style of the original INP.
    """
    value = float(x)
    if not math.isfinite(value):
        raise ValueError("Non-finite material property: %r" % x)
    nearest = round(value)
    if abs(value - nearest) <= 1.0e-12 * max(1.0, abs(value)):
        return "%d." % int(nearest)
    text = fmt.format(value)
    # Keep a real-looking token when a custom format returns an integer string.
    if not any(ch in text.lower() for ch in (".", "e")):
        text += "."
    return text


def chunked(seq: Sequence, n: int) -> Iterable[Sequence]:
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def format_data_lines(values: Sequence, max_per_line: int, float_fmt: str) -> List[str]:
    """Format Abaqus *User Material data.

    Abaqus accepts at most eight constants on one data line. Therefore the
    required nine properties are deliberately written as 8 + 1 lines. This is
    not an extra material block; the second line continues the same
    ``*User Material, constants=9`` definition.
    """
    if int(max_per_line) <= 0 or int(max_per_line) > 8:
        raise ValueError("MAX_VALUES_PER_LINE must be in 1..8 for Abaqus material data.")
    str_values = [format_abaqus_real(v, float_fmt) for v in values]
    return [" " + ", ".join(part) + "\n" for part in chunked(str_values, int(max_per_line))]

def normalize_rve_name(rve_id: int) -> str:
    return "RVE_%03d" % int(rve_id)


def case_key(case: CaseItem) -> str:
    return "%s_%s_%s" % (case.case_id, case.rate_tag, case.temp_tag)


# =============================================================================
# 2. Case-control replacement helpers
# =============================================================================

def replace_temperature(lines: List[str], temp_value: str) -> Tuple[List[str], int]:
    temp_s = str(temp_value)
    changed = 0
    i = 0
    pattern = re.compile(r"^(.*?TEMP_NODESET\s*,\s*)" + NUM + r"(.*)$", flags=re.IGNORECASE)

    while i < len(lines):
        cl = compact_lower(lines[i])
        if cl.startswith("*initialconditions") and "type=temperature" in cl:
            j = i + 1
            while j < len(lines):
                content, eol = split_eol_text(lines[j])
                stripped = content.strip()
                if stripped.startswith("**") or stripped == "":
                    j += 1
                    continue
                if stripped.startswith("*"):
                    break
                if "TEMP_NODESET" in content.upper():
                    new_content, n = pattern.subn(lambda m: m.group(1) + temp_s + m.group(2), content, count=1)
                    if n != 1:
                        raise RuntimeError("Found TEMP_NODESET line but failed to replace temperature.")
                    lines[j] = new_content + eol
                    changed += 1
                    break
                j += 1
        i += 1

    if changed == 0:
        raise RuntimeError("No temperature definition found after *Initial Conditions, type=TEMPERATURE.")
    return lines, changed


def _amp_token(value: str) -> str:
    """Abaqus-friendly amplitude token while retaining configured precision."""
    raw = str(value).strip()
    x = float(raw.replace("D", "E").replace("d", "e"))
    if abs(x - round(x)) <= 1.0e-14:
        return "%d." % int(round(x))
    return raw


def _normalized_amplitude_points(
    amplitude_points: Sequence[Tuple[str, str]]
) -> Tuple[Tuple[float, float], ...]:
    if len(amplitude_points) < 2:
        raise ValueError("Amplitude must contain at least two (time, value) points.")
    pts: List[Tuple[float, float]] = []
    for t_raw, a_raw in amplitude_points:
        t = float(str(t_raw).replace("D", "E").replace("d", "e"))
        a = float(str(a_raw).replace("D", "E").replace("d", "e"))
        if not math.isfinite(t) or not math.isfinite(a):
            raise ValueError("Non-finite amplitude point: %r" % ((t_raw, a_raw),))
        pts.append((t, a))
    for i in range(1, len(pts)):
        if not pts[i][0] > pts[i - 1][0]:
            raise ValueError("Amplitude times must be strictly increasing: %s" % (pts,))
    return tuple(pts)


def replace_amplitude(
    lines: List[str],
    amplitude_points: Sequence[Tuple[str, str]],
    cfg: Config,
) -> Tuple[List[str], int]:
    """Replace the complete AMP-1 history.

    For the standard monotonic history ``(0,0) -> (t_end,1)``, the function
    intentionally follows the legacy 04 behavior: it only replaces the third
    number on the existing four-value data line. This keeps monotonic tension
    and compression outputs directly comparable with the previous strict 04.

    For reversal histories, all amplitude data values are replaced with the
    configured multi-point history.
    """
    desired = _normalized_amplitude_points(amplitude_points)
    target = "name=" + str(cfg.BOUNDARY_AMPLITUDE_NAME).lower().replace(" ", "")

    keyword_index: Optional[int] = None
    for i, line in enumerate(lines):
        cl = compact_lower(line)
        if cl.startswith("*amplitude") and target in cl:
            keyword_index = i
            break
    if keyword_index is None:
        raise RuntimeError(
            "No *Amplitude, name=%s keyword found." % cfg.BOUNDARY_AMPLITUDE_NAME
        )

    block_end = len(lines)
    for j in range(keyword_index + 1, len(lines)):
        if lines[j].lstrip().startswith("*") and not lines[j].lstrip().startswith("**"):
            block_end = j
            break

    data_indices: List[int] = []
    existing_values: List[float] = []
    for j in range(keyword_index + 1, block_end):
        stripped = lines[j].strip()
        if not stripped or stripped.startswith("**"):
            continue
        data_indices.append(j)
        for token in stripped.split(","):
            token = token.strip()
            if token:
                existing_values.append(float(token.replace("D", "E").replace("d", "e")))

    if not data_indices:
        raise RuntimeError(
            "No amplitude data found after *Amplitude, name=%s."
            % cfg.BOUNDARY_AMPLITUDE_NAME
        )

    # Preserve the old output text exactly for the two monotonic groups.
    legacy_monotonic = (
        len(desired) == 2
        and np.allclose(np.asarray(desired[0]), np.asarray((0.0, 0.0)), rtol=0.0, atol=1.0e-14)
        and abs(desired[1][1] - 1.0) <= 1.0e-14
        and len(data_indices) == 1
        and len(existing_values) == 4
    )
    if legacy_monotonic:
        j = data_indices[0]
        content, eol = split_eol_text(lines[j])
        parts = content.split(",")
        if len(parts) < 4:
            raise RuntimeError("Malformed four-value amplitude data line: %s" % content)
        parts[2] = "             " + str(amplitude_points[-1][0])
        lines[j] = ",".join(parts) + eol
        return lines, 1

    first_data = data_indices[0]
    last_data = data_indices[-1] + 1
    _, eol = split_eol_text(lines[first_data])
    if not eol:
        _, eol = split_eol_text(lines[keyword_index])
    if not eol:
        eol = "\n"

    tokens: List[str] = []
    for t_raw, a_raw in amplitude_points:
        tokens.extend([_amp_token(t_raw), _amp_token(a_raw)])

    # Abaqus accepts up to eight values per data line. Current reversal paths
    # contain six values and are therefore written on one line.
    new_data_lines: List[str] = []
    for part in chunked(tokens, 8):
        new_data_lines.append(" " + ", ".join(part) + eol)

    lines[first_data:last_data] = new_data_lines
    return lines, 1


def replace_static(lines: List[str], static_line: str) -> Tuple[List[str], int]:
    changed = 0
    for i in range(len(lines) - 1):
        if keyword_lower(lines[i]).startswith("*static"):
            j = i + 1
            while j < len(lines):
                content, eol = split_eol_text(lines[j])
                stripped = content.strip()
                if stripped.startswith("**") or stripped == "":
                    j += 1
                    continue
                if stripped.startswith("*"):
                    break
                lines[j] = str(static_line) + eol
                changed += 1
                break
            break

    if changed == 0:
        raise RuntimeError("No *Static data line found.")
    return lines, changed


def replace_output_intervals(lines: List[str], interval: str) -> Tuple[List[str], int]:
    """Replace every ``time interval=...`` option on *Output lines.

    The option may appear anywhere in the keyword line, for example both of
    the following are supported:

        *Output, field, time interval=0.06
        *Output, field, variable=PRESELECT, time interval=0.06

    Only *Output field/history keyword lines are touched.
    """
    interval_s = str(interval)
    changed = 0
    time_pattern = re.compile(
        r"(\btime\s+interval\s*=\s*)" + NUM,
        flags=re.IGNORECASE,
    )

    for i in range(len(lines)):
        content, eol = split_eol_text(lines[i])
        low = content.lstrip().lower()
        if not low.startswith("*output"):
            continue
        if not re.search(r"^\s*\*Output\s*,.*\b(field|history)\b", content, flags=re.IGNORECASE):
            continue
        new_content, n = time_pattern.subn(
            lambda m: m.group(1) + interval_s,
            content,
            count=1,
        )
        if n == 1:
            lines[i] = new_content + eol
            changed += 1

    if changed == 0:
        raise RuntimeError("No *Output field/history line containing time interval=... was found.")
    return lines, changed

def replace_boundary_line(lines: List[str], boundary_line: str, cfg: Config) -> Tuple[List[str], int]:
    """Replace the target PBC boundary data line under *Boundary, amplitude=AMP-1.

    Unlike the previous macro_h33-only replacement, this replaces the whole
    data line, so the reference point name, DOF range, and value can all be
    configured from CASES, for example:
        PBC_REFMACRO3, 3, 3, 0.162
        PBC_REFMACRO1, 1, 1, 0.162
        PBC_REFMACRO3, 3, 3, -0.162
    """
    new_line = str(boundary_line).strip()
    if not new_line:
        raise RuntimeError("Empty boundary_line in CASES.")

    changed = 0
    target_amp = str(cfg.BOUNDARY_AMPLITUDE_NAME).lower().replace(" ", "")
    target_name = str(cfg.BOUNDARY_TARGET_NAME).strip().upper()

    i = 0
    while i < len(lines):
        cl = compact_lower(lines[i])
        if cl.startswith("*boundary") and ("amplitude=" + target_amp) in cl:
            j = i + 1
            while j < len(lines):
                content, eol = split_eol_text(lines[j])
                stripped = content.strip()
                if stripped.startswith("**") or stripped == "":
                    j += 1
                    continue
                if stripped.startswith("*"):
                    break

                first_token = stripped.split(",", 1)[0].strip().upper()
                if first_token == target_name:
                    lines[j] = new_line + eol
                    changed += 1
                    break

                j += 1
        i += 1

    if changed == 0:
        raise RuntimeError(
            "No target boundary line found under *Boundary, amplitude=%s for target %s."
            % (cfg.BOUNDARY_AMPLITUDE_NAME, cfg.BOUNDARY_TARGET_NAME)
        )
    return lines, changed


def apply_case_control(lines: Sequence[str], case: CaseItem, cfg: Config) -> Tuple[List[str], Dict[str, int]]:
    out = list(lines)
    counts: Dict[str, int] = {}
    out, counts["temperature"] = replace_temperature(out, case.temperature)
    out, counts["amplitude"] = replace_amplitude(out, case.amplitude_points, cfg)
    out, counts["static"] = replace_static(out, case.static_line)
    out, counts["output_interval"] = replace_output_intervals(out, case.output_interval)
    out, counts["boundary_line"] = replace_boundary_line(out, case.boundary_line, cfg)
    for key in ("temperature", "amplitude", "static", "boundary_line"):
        if counts[key] != 1:
            raise RuntimeError("Case-control replacement '%s' must occur exactly once; found %d." % (key, counts[key]))
    if counts["output_interval"] <= 0:
        raise RuntimeError("No output interval was replaced.")
    return out, counts


# =============================================================================
# 3. RVE injection table loading
# =============================================================================

def detect_rve_ids(rve_root: Path) -> List[int]:
    ids = []
    for p in rve_root.iterdir():
        if not p.is_dir():
            continue
        m = re.match(r"RVE_(\d+)$", p.name, re.IGNORECASE)
        if m and (p / "inp_injection_table.csv").exists():
            ids.append(int(m.group(1)))
    return sorted(ids)


def normalize_rve_ids(rve_ids) -> List[int]:
    if isinstance(rve_ids, int):
        return [int(rve_ids)]
    if isinstance(rve_ids, str):
        return [int(x.strip()) for x in rve_ids.split(",") if x.strip()]
    return [int(x) for x in rve_ids]


def load_injection_table(path: Path, cfg: Config) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError("RVE injection table not found: %s" % str(path))

    df = pd.read_csv(path)
    required = {"Element_ID", "Phase", "N_diff", "Orientation_ID", "phi1", "Phi", "phi2", "Sample_Weight"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError("Injection table missing required columns %s in %s" % (sorted(missing), str(path)))

    if "N_total" not in df.columns:
        df["N_total"] = cfg.N_TOTAL_NEIGHBORS

    df = df.copy()
    for col in ["Element_ID", "Phase", "N_diff", "N_total"]:
        df[col] = pd.to_numeric(df[col], errors="raise").astype(int)
    df["Orientation_ID"] = df["Orientation_ID"].astype(str)
    for col in ["phi1", "Phi", "phi2", "Sample_Weight"]:
        df[col] = pd.to_numeric(df[col], errors="raise")

    if df["Element_ID"].duplicated().any():
        dup = df.loc[df["Element_ID"].duplicated(), "Element_ID"].head(10).tolist()
        raise ValueError("Duplicated Element_ID in %s, examples: %s" % (str(path), dup))
    if (df["Element_ID"] <= 0).any():
        raise ValueError("Element_ID must be positive in %s" % str(path))

    allowed_phases = {int(cfg.BCC_PHASE_ID), int(cfg.HCP_PHASE_ID)}
    actual_phases = set(df["Phase"].astype(int).unique().tolist())
    if not actual_phases.issubset(allowed_phases):
        raise ValueError("Unexpected Phase values %s; allowed=%s" % (sorted(actual_phases), sorted(allowed_phases)))

    if (df["N_total"] < 0).any() or (df["N_total"] > int(cfg.N_TOTAL_NEIGHBORS)).any():
        raise ValueError("N_total must be within 0..%d" % int(cfg.N_TOTAL_NEIGHBORS))
    if (df["N_diff"] < 0).any() or (df["N_diff"] > df["N_total"]).any():
        raise ValueError("N_diff must satisfy 0 <= N_diff <= N_total")
    if (df["Sample_Weight"] <= 0.0).any():
        raise ValueError("Sample_Weight must be positive")

    numeric = df[["phi1", "Phi", "phi2", "Sample_Weight"]].to_numpy(dtype=float)
    if not np.isfinite(numeric).all():
        raise ValueError("Non-finite Euler angle or Sample_Weight in %s" % str(path))

    return df.sort_values("Element_ID").reset_index(drop=True)


# =============================================================================
# 4. INP template parsing / validation
# =============================================================================

def find_first_part_range(lines: Sequence[str]) -> Tuple[int, int]:
    start = None
    for i, line in enumerate(lines):
        if keyword_lower(line).startswith("*part"):
            start = i
            break
    if start is None:
        raise RuntimeError("No *Part block found in template INP.")
    for j in range(start + 1, len(lines)):
        if keyword_lower(lines[j]).startswith("*end part"):
            return start, j
    raise RuntimeError("No *End Part found after first *Part.")


def find_microstructure_replace_range_in_part(lines: Sequence[str], cfg: Config) -> Tuple[int, int]:
    part_start, end_part = find_first_part_range(lines)
    grain_re = re.compile(r"^\s*\*elset\s*,.*\belset\s*=\s*" + re.escape(cfg.GRAIN_SET_PREFIX), re.IGNORECASE)
    start = None
    for i in range(part_start + 1, end_part):
        if grain_re.search(lines[i]):
            start = i
            break
    if start is None:
        raise RuntimeError(
            "Could not find first '*Elset, elset=%s...' inside Part. "
            "Please check the template." % cfg.GRAIN_SET_PREFIX
        )
    return start, end_part


def parse_template_element_ids(lines: Sequence[str]) -> List[int]:
    part_start, end_part = find_first_part_range(lines)
    ids: List[int] = []
    mode = None
    reading_c3d8 = False
    for line in lines[part_start + 1:end_part]:
        stripped = line.strip()
        if not stripped or stripped.startswith("**"):
            continue
        low = stripped.lower()
        if is_keyword(stripped):
            if low.startswith("*element") and "type=c3d8" in low:
                mode = "element"
                reading_c3d8 = True
            else:
                mode = None
                reading_c3d8 = False
            continue
        if mode == "element" and reading_c3d8:
            parts = [x.strip() for x in stripped.replace("\t", " ").split(",") if x.strip()]
            if parts:
                try:
                    ids.append(int(float(parts[0])))
                except Exception:
                    pass
    return ids


def validate_injection_against_template(df: pd.DataFrame, lines: Sequence[str], template_name: str) -> None:
    elem_ids = set(parse_template_element_ids(lines))
    if not elem_ids:
        raise RuntimeError("No C3D8 elements parsed from template: %s" % template_name)
    inj_ids = set(df["Element_ID"].astype(int).tolist())
    missing_in_template = sorted(inj_ids - elem_ids)
    missing_in_injection = sorted(elem_ids - inj_ids)
    if missing_in_template or missing_in_injection:
        msg = ["Element_ID mismatch for template %s" % template_name]
        if missing_in_template:
            msg.append("  Injection has IDs not in template, first 20: %s" % missing_in_template[:20])
        if missing_in_injection:
            msg.append("  Template has IDs not in injection, first 20: %s" % missing_in_injection[:20])
        raise RuntimeError("\n".join(msg))


# =============================================================================
# 5. Material prototype extraction / generation
# =============================================================================

def find_material_region(lines: Sequence[str]) -> Optional[Tuple[int, int]]:
    """Return only the material-definition region.

    It must stop before the Initial boundary conditions / predefined field /
    analysis step. This prevents material injection from deleting the PBC
    anchors or the temperature assignment.
    """
    start = None
    for i, line in enumerate(lines):
        if keyword_lower(line).startswith("*material"):
            start = i
            break
    if start is None:
        return None

    end_patterns = (
        r"^\s*\*\*\s*BOUNDARY\s+CONDITIONS\b",
        r"^\s*\*\*\s*PREDEFINED\s+FIELDS\b",
        r"^\s*\*\*\s*STEP\b",
        r"^\s*\*\*\s*INTERACTIONS?\b",
        r"^\s*\*\*\s*LOADS?\b",
        r"^\s*\*\*\s*OUTPUT\s+REQUESTS\b",
        r"^\s*\*Boundary\b",
        r"^\s*\*Initial\s+Conditions\b",
        r"^\s*\*Step\b",
        r"^\s*\*Assembly\b",
        r"^\s*\*End\s+Assembly\b",
    )
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if any(re.search(p, lines[j], flags=re.IGNORECASE) for p in end_patterns):
            end = j
            break
    while end > start and lines[end - 1].strip() in ("", "**"):
        end -= 1
    return start, end


def split_material_blocks(lines: Sequence[str], material_region: Tuple[int, int]) -> List[List[str]]:
    start, end = material_region
    starts = [i for i in range(start, end) if keyword_lower(lines[i]).startswith("*material")]
    if not starts:
        return []
    bounds = starts[1:] + [end]
    return [list(lines[s:e]) for s, e in zip(starts, bounds)]


def material_keyword_signature(block: Sequence[str]) -> Tuple[str, ...]:
    signature: List[str] = []
    for line in block:
        stripped = line.strip()
        if not stripped or stripped.startswith("**"):
            continue
        if stripped.startswith("*"):
            signature.append(stripped.split(",", 1)[0].strip().lower())
    return tuple(signature)


def parse_declared_constants(keyword_line: str) -> Optional[int]:
    m = re.search(r"\bconstants\s*=\s*(\d+)", keyword_line, flags=re.IGNORECASE)
    return int(m.group(1)) if m else None


def parse_keyword_data_values(block: Sequence[str], keyword_prefix: str) -> Tuple[Optional[str], List[float]]:
    for i, line in enumerate(block):
        if keyword_lower(line).startswith(keyword_prefix.lower()):
            values: List[float] = []
            j = i + 1
            while j < len(block):
                stripped = block[j].strip()
                if stripped.startswith("*"):
                    break
                if stripped and not stripped.startswith("**"):
                    for token in stripped.split(","):
                        token = token.strip()
                        if token:
                            values.append(float(token.replace("D", "E").replace("d", "e")))
                j += 1
            return line, values
    return None, []


def validate_template_material_structure(lines: Sequence[str], cfg: Config) -> List[str]:
    region = find_material_region(lines)
    if region is None:
        raise RuntimeError("The template contains no *Material region.")
    blocks = split_material_blocks(lines, region)
    if not blocks:
        raise RuntimeError("The template material region contains no material blocks.")

    expected_signature = material_keyword_signature(blocks[0])
    required_signature = ("*material", "*depvar", "*user material")
    if expected_signature != required_signature:
        raise RuntimeError(
            "Unexpected original material keyword order. Expected %s, found %s"
            % (required_signature, expected_signature)
        )

    for idx, block in enumerate(blocks, start=1):
        sig = material_keyword_signature(block)
        if cfg.REQUIRE_UNIFORM_TEMPLATE_MATERIAL_STRUCTURE and sig != expected_signature:
            raise RuntimeError("Original material block %d has a different keyword structure: %s" % (idx, sig))

        _, depvar_values = parse_keyword_data_values(block, "*depvar")
        if len(depvar_values) != 1 or int(round(depvar_values[0])) != int(cfg.EXPECTED_DEPVAR_COUNT):
            raise RuntimeError(
                "Original material block %d does not define *Depvar = %d"
                % (idx, int(cfg.EXPECTED_DEPVAR_COUNT))
            )

        user_line, user_values = parse_keyword_data_values(block, "*user material")
        declared = parse_declared_constants(user_line or "")
        if declared is None or declared != len(user_values):
            raise RuntimeError(
                "Original material block %d has inconsistent *User Material constants: declared=%s, data=%d"
                % (idx, declared, len(user_values))
            )
    return blocks[0]


def make_user_material_constants(row: pd.Series, cfg: Config) -> List[float]:
    # PROPS(1:9): phi1, Phi, phi2, feature/element id, phase id,
    # readfromprops flag, N_total, N_diff, Sample_Weight.
    return [
        float(row["phi1"]),
        float(row["Phi"]),
        float(row["phi2"]),
        float(int(row["Element_ID"])),
        float(int(row["Phase"])),
        float(cfg.RESERVED_CONSTANT_6),
        float(int(row.get("N_total", cfg.N_TOTAL_NEIGHBORS))),
        float(int(row["N_diff"])),
        float(row["Sample_Weight"]),
    ]


def material_name_for_element(eid: int, cfg: Config) -> str:
    return "%s%d" % (cfg.MATERIAL_PREFIX, int(eid))


def grain_set_name_for_element(eid: int, cfg: Config) -> str:
    return "%s%d" % (cfg.GRAIN_SET_PREFIX, int(eid))


def transform_material_prototype(
    prototype_lines: Sequence[str],
    material_name: str,
    constants: Sequence[float],
    cfg: Config,
) -> List[str]:
    """Clone the original material block and replace only name/user constants."""
    out: List[str] = []
    i = 0
    user_written = False
    while i < len(prototype_lines):
        line = prototype_lines[i]
        low = keyword_lower(line)
        if low.startswith("*material"):
            out.append("*Material, name=%s\n" % material_name)
            i += 1
            continue
        if low.startswith("*user material"):
            out.append("*User Material, constants=%d\n" % int(cfg.USER_MATERIAL_CONSTANTS))
            out.extend(format_data_lines(constants, cfg.MAX_VALUES_PER_LINE, cfg.FLOAT_FORMAT))
            user_written = True
            i += 1
            # Delete only the old *User Material data lines. Preserve the next
            # keyword and every other material subkeyword exactly.
            while i < len(prototype_lines) and not is_keyword(prototype_lines[i]):
                i += 1
            continue
        out.append(line)
        i += 1

    if not user_written:
        raise RuntimeError("The original material prototype has no *User Material keyword.")
    return out


def make_minimal_material_block(material_name: str, constants: Sequence[float], cfg: Config) -> List[str]:
    if not cfg.FALLBACK_MINIMAL_MATERIAL:
        raise RuntimeError("Minimal material fallback is disabled; a valid original prototype is required.")
    lines = [
        "*Material, name=%s\n" % material_name,
        "*Depvar\n",
        "    %d,\n" % int(cfg.EXPECTED_DEPVAR_COUNT),
        "*User Material, constants=%d\n" % int(cfg.USER_MATERIAL_CONSTANTS),
    ]
    lines.extend(format_data_lines(constants, cfg.MAX_VALUES_PER_LINE, cfg.FLOAT_FORMAT))
    return lines


def generate_material_blocks(df: pd.DataFrame, template_lines: Sequence[str], cfg: Config) -> List[str]:
    prototype: Optional[List[str]] = None
    if cfg.USE_TEMPLATE_MATERIAL_PROTOTYPE:
        prototype = validate_template_material_structure(template_lines, cfg)
    if prototype is None and not cfg.FALLBACK_MINIMAL_MATERIAL:
        raise RuntimeError("No valid material prototype found and FALLBACK_MINIMAL_MATERIAL=False.")

    out: List[str] = []
    out.append("** ----------------------------------------------------------------\n")
    out.append("** Element-wise materials generated by 04_inject_rve_info_to_inp_with_case_bc_control_strict.py\n")
    out.append("** PROPS: phi1, Phi, phi2, Element_ID, Phase, 0, N_total, N_diff, Sample_Weight\n")
    out.append("** Nine constants are written on 8 + 1 Abaqus data lines.\n")
    out.append("** ----------------------------------------------------------------\n")

    for _, row in df.iterrows():
        eid = int(row["Element_ID"])
        mat_name = material_name_for_element(eid, cfg)
        constants = make_user_material_constants(row, cfg)
        if prototype is not None:
            out.extend(transform_material_prototype(prototype, mat_name, constants, cfg))
        else:
            out.extend(make_minimal_material_block(mat_name, constants, cfg))
    return out


# =============================================================================
# 6. Part microstructure block generation
# =============================================================================

def elset_lines(name: str, ids: Sequence[int], cfg: Config) -> List[str]:
    lines = ["*Elset, elset=%s\n" % name]
    ids_sorted = [int(x) for x in ids]
    for part in chunked(ids_sorted, cfg.ELSET_IDS_PER_LINE):
        lines.append(", ".join(str(int(v)) for v in part) + "\n")
    return lines


def generate_part_microstructure_block(df: pd.DataFrame, cfg: Config) -> List[str]:
    """Generate the Part block in the same high-level order as the original INP.

    Order: GRAIN elsets -> PHASE elsets -> Section assignments.
    """
    lines: List[str] = []
    lines.append("** ----------------------------------------------------------------\n")
    lines.append("** RVE microstructure block generated by 04_inject_rve_info_to_inp_with_case_bc_control_strict.py\n")
    lines.append("** ----------------------------------------------------------------\n")

    lines.append("** Element-wise grain elsets\n")
    for eid in df["Element_ID"].astype(int).tolist():
        lines.extend(elset_lines(grain_set_name_for_element(eid, cfg), [eid], cfg))

    lines.append("** Phase elsets\n")
    for phase in sorted(df["Phase"].unique()):
        ids = df.loc[df["Phase"] == phase, "Element_ID"].astype(int).tolist()
        lines.extend(elset_lines("%s%d" % (cfg.PHASE_SET_PREFIX, int(phase)), ids, cfg))

    lines.append("** Section assignments\n")
    for eid in df["Element_ID"].astype(int).tolist():
        lines.append("** Section: Section-%d-GRAIN-%d\n" % (eid, eid))
        lines.append("*Solid Section, elset=%s, material=%s\n" % (
            grain_set_name_for_element(eid, cfg),
            material_name_for_element(eid, cfg),
        ))
        lines.append(",\n")
    return lines


# =============================================================================
# 7. INP injection
# =============================================================================

def replace_part_microstructure(lines: Sequence[str], new_block: Sequence[str], cfg: Config) -> List[str]:
    start, end = find_microstructure_replace_range_in_part(lines, cfg)
    return list(lines[:start]) + list(new_block) + list(lines[end:])


def replace_materials(lines: Sequence[str], new_materials: Sequence[str], cfg: Config) -> List[str]:
    region = find_material_region(lines)
    if region is None:
        for i, line in enumerate(lines):
            if keyword_lower(line).startswith("*step"):
                return list(lines[:i]) + list(new_materials) + list(lines[i:])
        return list(lines) + list(new_materials)

    start, end = region
    return list(lines[:start]) + list(new_materials) + list(lines[end:])


def count_keyword(lines: Sequence[str], keyword: str) -> int:
    key = keyword.strip().lower()
    return sum(1 for line in lines if keyword_lower(line).startswith(key))


def find_block(lines: Sequence[str], start_keyword: str, end_keyword: str) -> List[str]:
    start = None
    for i, line in enumerate(lines):
        if keyword_lower(line).startswith(start_keyword.lower()):
            start = i
            break
    if start is None:
        raise RuntimeError("Block start not found: %s" % start_keyword)
    for j in range(start + 1, len(lines)):
        if keyword_lower(lines[j]).startswith(end_keyword.lower()):
            return list(lines[start:j + 1])
    raise RuntimeError("Block end not found: %s" % end_keyword)


def output_interval_values(lines: Sequence[str]) -> List[float]:
    values: List[float] = []
    pattern = re.compile(r"\btime\s+interval\s*=\s*(" + NUM + r")", flags=re.IGNORECASE)
    for line in lines:
        content, _ = split_eol_text(line)
        if not re.search(r"^\s*\*Output\s*,.*\b(field|history)\b", content, flags=re.IGNORECASE):
            continue
        m = pattern.search(content)
        if m:
            values.append(float(m.group(1).replace("D", "E").replace("d", "e")))
    return values


def configured_temperature_value(lines: Sequence[str]) -> Optional[float]:
    pattern = re.compile(r"^\s*TEMP_NODESET\s*,\s*(" + NUM + r")", flags=re.IGNORECASE)
    inside = False
    for line in lines:
        cl = compact_lower(line)
        if cl.startswith("*initialconditions") and "type=temperature" in cl:
            inside = True
            continue
        if inside:
            stripped = line.strip()
            if stripped.startswith("**") or stripped == "":
                continue
            if stripped.startswith("*"):
                break
            m = pattern.search(line)
            if m:
                return float(m.group(1).replace("D", "E").replace("d", "e"))
    return None


def target_boundary_data_lines(lines: Sequence[str], cfg: Config) -> List[str]:
    found: List[str] = []
    target_amp = str(cfg.BOUNDARY_AMPLITUDE_NAME).lower().replace(" ", "")
    target_name = str(cfg.BOUNDARY_TARGET_NAME).strip().upper()
    i = 0
    while i < len(lines):
        cl = compact_lower(lines[i])
        if cl.startswith("*boundary") and ("amplitude=" + target_amp) in cl:
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                if stripped.startswith("**") or stripped == "":
                    j += 1
                    continue
                if stripped.startswith("*"):
                    break
                if stripped.split(",", 1)[0].strip().upper() == target_name:
                    found.append(stripped)
                j += 1
        i += 1
    return found


def amplitude_point_values(
    lines: Sequence[str], amplitude_name: str
) -> Optional[List[Tuple[float, float]]]:
    target = str(amplitude_name).lower().replace(" ", "")
    for i, line in enumerate(lines):
        cl = compact_lower(line)
        if not (cl.startswith("*amplitude") and ("name=" + target) in cl):
            continue

        values: List[float] = []
        j = i + 1
        while j < len(lines):
            stripped = lines[j].strip()
            if stripped.startswith("*") and not stripped.startswith("**"):
                break
            if stripped and not stripped.startswith("**"):
                for token in stripped.split(","):
                    token = token.strip()
                    if token:
                        values.append(float(token.replace("D", "E").replace("d", "e")))
            j += 1

        if len(values) < 4 or len(values) % 2 != 0:
            return None
        return [(values[k], values[k + 1]) for k in range(0, len(values), 2)]
    return None


def amplitude_end_time_value(lines: Sequence[str], amplitude_name: str) -> Optional[float]:
    points = amplitude_point_values(lines, amplitude_name)
    return None if not points else float(points[-1][0])


def static_data_values(lines: Sequence[str]) -> Optional[List[float]]:
    for i, line in enumerate(lines):
        if keyword_lower(line).startswith("*static"):
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                if not stripped or stripped.startswith("**"):
                    j += 1
                    continue
                if stripped.startswith("*"):
                    return None
                return [float(x.strip().replace("D", "E").replace("d", "e"))
                        for x in stripped.split(",") if x.strip()]
    return None


def parse_named_elsets_in_first_part(lines: Sequence[str]) -> Dict[str, List[int]]:
    part_start, end_part = find_first_part_range(lines)
    result: Dict[str, List[int]] = {}
    i = part_start + 1
    while i < end_part:
        line = lines[i]
        if re.match(r"^\s*\*Elset\b", line, flags=re.IGNORECASE):
            opts = parse_keyword_options(line)
            name = opts.get("elset")
            generate = "generate" in line.lower()
            vals: List[int] = []
            j = i + 1
            while j < end_part and not is_keyword(lines[j]):
                stripped = lines[j].strip()
                if stripped and not stripped.startswith("**"):
                    vals.extend(int(float(x.strip())) for x in stripped.split(",") if x.strip())
                j += 1
            if name:
                if generate and len(vals) >= 3:
                    expanded: List[int] = []
                    for k in range(0, len(vals), 3):
                        a, b, inc = vals[k:k+3]
                        expanded.extend(range(a, b + (1 if inc > 0 else -1), inc))
                    vals = expanded
                result[name.upper()] = vals
            i = j
            continue
        i += 1
    return result


def parse_solid_section_map(lines: Sequence[str]) -> Dict[str, str]:
    result: Dict[str, str] = {}
    for line in lines:
        if re.match(r"^\s*\*Solid\s+Section\b", line, flags=re.IGNORECASE):
            opts = parse_keyword_options(line)
            elset = opts.get("elset")
            material = opts.get("material")
            if elset and material:
                result[elset.upper()] = material.upper()
    return result


def validate_generated_materials_and_sections(
    output_lines: Sequence[str], df: pd.DataFrame, cfg: Config
) -> List[str]:
    errors: List[str] = []
    region = find_material_region(output_lines)
    if region is None:
        return ["Generated material region is missing."]
    blocks = split_material_blocks(output_lines, region)
    expected_rows = {int(r["Element_ID"]): r for _, r in df.iterrows()}
    if len(blocks) != len(expected_rows):
        errors.append("Generated material block count mismatch: expected=%d, found=%d" % (len(expected_rows), len(blocks)))
        return errors

    seen: set[int] = set()
    name_re = re.compile(r"^\s*\*Material\s*,.*\bname\s*=\s*" + re.escape(cfg.MATERIAL_PREFIX) + r"(\d+)\s*$", re.I)
    for block_index, block in enumerate(blocks, start=1):
        m = name_re.match(block[0].strip())
        if not m:
            errors.append("Material block %d has unexpected name line: %s" % (block_index, block[0].strip()))
            continue
        eid = int(m.group(1))
        if eid in seen:
            errors.append("Duplicated generated material for Element_ID=%d" % eid)
            continue
        seen.add(eid)
        if eid not in expected_rows:
            errors.append("Generated material refers to unknown Element_ID=%d" % eid)
            continue

        sig = material_keyword_signature(block)
        if sig != ("*material", "*depvar", "*user material"):
            errors.append("Material %d keyword order is %s" % (eid, sig))

        _, depvar_values = parse_keyword_data_values(block, "*depvar")
        if len(depvar_values) != 1 or int(round(depvar_values[0])) != int(cfg.EXPECTED_DEPVAR_COUNT):
            errors.append("Material %d has invalid *Depvar data: %s" % (eid, depvar_values))

        user_line, values = parse_keyword_data_values(block, "*user material")
        declared = parse_declared_constants(user_line or "")
        if declared != int(cfg.USER_MATERIAL_CONSTANTS):
            errors.append("Material %d declares constants=%s, expected=%d" % (eid, declared, int(cfg.USER_MATERIAL_CONSTANTS)))
            continue
        if len(values) != int(cfg.USER_MATERIAL_CONSTANTS):
            errors.append("Material %d contains %d constants, expected=%d" % (eid, len(values), int(cfg.USER_MATERIAL_CONSTANTS)))
            continue

        expected = make_user_material_constants(expected_rows[eid], cfg)
        if not np.allclose(np.asarray(values), np.asarray(expected), rtol=0.0, atol=1.0e-9):
            errors.append("Material %d constants do not match the injection table." % eid)

    missing = sorted(set(expected_rows) - seen)
    if missing:
        errors.append("Missing generated materials, first 20 Element_IDs: %s" % missing[:20])

    elsets = parse_named_elsets_in_first_part(output_lines)
    sections = parse_solid_section_map(output_lines)
    expected_ids = set(expected_rows)
    for eid in sorted(expected_ids):
        grain = grain_set_name_for_element(eid, cfg).upper()
        mat = material_name_for_element(eid, cfg).upper()
        if elsets.get(grain) != [eid]:
            errors.append("%s must contain only element %d." % (grain, eid))
            if len(errors) > 40:
                break
        if sections.get(grain) != mat:
            errors.append("Section mapping mismatch for %s: expected material=%s, found=%s" % (grain, mat, sections.get(grain)))
            if len(errors) > 40:
                break

    for phase in sorted(df["Phase"].unique()):
        name = ("%s%d" % (cfg.PHASE_SET_PREFIX, int(phase))).upper()
        expected_phase = set(df.loc[df["Phase"] == phase, "Element_ID"].astype(int).tolist())
        found_phase = set(elsets.get(name, []))
        if found_phase != expected_phase:
            errors.append("Phase elset %s does not match injection table (expected=%d, found=%d)." % (name, len(expected_phase), len(found_phase)))
    return errors


def validate_final_inp(
    template_lines: Sequence[str],
    output_lines: Sequence[str],
    df: pd.DataFrame,
    cfg: Config,
    case: Optional[CaseItem],
    output_name: str,
) -> Dict[str, object]:
    """Fail fast when anything outside the intended replacement areas changed."""
    errors: List[str] = []

    # The node/element/assembly prefix before the original Part microstructure
    # block must remain byte-for-byte identical.
    try:
        micro_start, _ = find_microstructure_replace_range_in_part(template_lines, cfg)
        if list(template_lines[:micro_start]) != list(output_lines[:micro_start]):
            errors.append("Content before the Part microstructure block changed unexpectedly.")
    except Exception as exc:
        errors.append("Part-prefix preservation check failed: %s" % exc)

    # Everything after the material region (Initial BCs, temperature field,
    # Step, loading and outputs) must remain exactly as it was after case control.
    try:
        t_region = find_material_region(template_lines)
        o_region = find_material_region(output_lines)
        if t_region is None or o_region is None:
            errors.append("Material region missing during tail-preservation check.")
        else:
            if list(template_lines[t_region[1]:]) != list(output_lines[o_region[1]:]):
                errors.append("Post-material analysis block changed unexpectedly.")
    except Exception as exc:
        errors.append("Post-material preservation check failed: %s" % exc)

    # Assembly, equations, sets and analysis skeleton must be preserved.
    if cfg.REQUIRE_ASSEMBLY_EXACTLY_PRESERVED:
        try:
            asm_before = find_block(template_lines, "*assembly", "*end assembly")
            asm_after = find_block(output_lines, "*assembly", "*end assembly")
            if asm_before != asm_after:
                errors.append("Assembly block changed, but it must be preserved exactly.")
        except Exception as exc:
            errors.append("Assembly preservation check failed: %s" % exc)

    protected_keywords = (
        "*nset",
        "*equation",
        "*boundary",
        "*initial conditions",
        "*amplitude",
        "*step",
        "*output",
    )
    for key in protected_keywords:
        before = count_keyword(template_lines, key)
        after = count_keyword(output_lines, key)
        if before != after:
            errors.append("Keyword count changed for %s: template=%d, output=%d" % (key, before, after))

    expected_n = int(len(df))
    n_mat = count_keyword(output_lines, "*material")
    n_sec = count_keyword(output_lines, "*solid section")
    if n_mat != expected_n:
        errors.append("Material count mismatch: expected=%d, output=%d" % (expected_n, n_mat))
    if n_sec != expected_n:
        errors.append("Solid Section count mismatch: expected=%d, output=%d" % (expected_n, n_sec))
    n_depvar = count_keyword(output_lines, "*depvar")
    n_user = count_keyword(output_lines, "*user material")
    if n_depvar != expected_n:
        errors.append("Depvar count mismatch: expected=%d, output=%d" % (expected_n, n_depvar))
    if n_user != expected_n:
        errors.append("User Material count mismatch: expected=%d, output=%d" % (expected_n, n_user))
    if cfg.VALIDATE_EVERY_GENERATED_MATERIAL:
        errors.extend(validate_generated_materials_and_sections(output_lines, df, cfg))

    # Confirm all configured case controls survived the later RVE injection.
    temp_value = configured_temperature_value(output_lines)
    out_intervals = output_interval_values(output_lines)
    boundary_hits = target_boundary_data_lines(output_lines, cfg)

    if case is not None:
        expected_temp = float(case.temperature)
        if temp_value is None:
            errors.append("The final INP has no TEMP_NODESET temperature assignment.")
        elif abs(temp_value - expected_temp) > 1.0e-9:
            errors.append("Temperature mismatch: expected=%g, output=%g" % (expected_temp, temp_value))

        amp_points = amplitude_point_values(output_lines, cfg.BOUNDARY_AMPLITUDE_NAME)
        expected_amp_points = [
            (float(str(t).replace("D", "E").replace("d", "e")),
             float(str(a).replace("D", "E").replace("d", "e")))
            for t, a in case.amplitude_points
        ]
        if (
            amp_points is None
            or len(amp_points) != len(expected_amp_points)
            or not np.allclose(
                np.asarray(amp_points, dtype=float),
                np.asarray(expected_amp_points, dtype=float),
                rtol=0.0,
                atol=1.0e-12,
            )
        ):
            errors.append(
                "Amplitude history mismatch: expected=%s, output=%s"
                % (expected_amp_points, amp_points)
            )

        static_values = static_data_values(output_lines)
        expected_static = [float(x.strip().replace("D", "E").replace("d", "e"))
                           for x in str(case.static_line).split(",") if x.strip()]
        if static_values is None or len(static_values) != len(expected_static) or not np.allclose(
            np.asarray(static_values), np.asarray(expected_static), rtol=0.0, atol=1.0e-14
        ):
            errors.append("*Static data mismatch: expected=%s, output=%s" % (expected_static, static_values))

        expected_interval = float(case.output_interval)
        if not out_intervals:
            errors.append("No *Output field/history time interval was found in the final INP.")
        else:
            bad = [v for v in out_intervals if abs(v - expected_interval) > 1.0e-12]
            if bad:
                errors.append(
                    "Not all output intervals were updated. expected=%g, values=%s"
                    % (expected_interval, out_intervals)
                )
            if cfg.REQUIRE_ALL_OUTPUT_INTERVALS_EQUAL and any(
                abs(v - out_intervals[0]) > 1.0e-12 for v in out_intervals[1:]
            ):
                errors.append("Output time intervals are not identical: %s" % out_intervals)

        expected_boundary = str(case.boundary_line).strip().replace(" ", "").upper()
        normalized_hits = [x.replace(" ", "").upper() for x in boundary_hits]
        if expected_boundary not in normalized_hits:
            errors.append(
                "Configured loading boundary line is missing. expected='%s', found=%s"
                % (case.boundary_line, boundary_hits)
            )

    # Phase sets must cover exactly the injected element IDs.
    phase_total = int(sum((df["Phase"] == p).sum() for p in df["Phase"].unique()))
    if phase_total != expected_n:
        errors.append("Internal phase-table count mismatch: phase_total=%d, expected=%d" % (phase_total, expected_n))

    if errors:
        raise RuntimeError(
            "Final INP validation failed for %s:\n  - %s"
            % (output_name, "\n  - ".join(errors))
        )

    return {
        "validation_status": "Passed",
        "validation_boundary_count": count_keyword(output_lines, "*boundary"),
        "validation_initial_conditions_count": count_keyword(output_lines, "*initial conditions"),
        "validation_equation_count": count_keyword(output_lines, "*equation"),
        "validation_nset_count": count_keyword(output_lines, "*nset"),
        "validation_depvar_count": count_keyword(output_lines, "*depvar"),
        "validation_user_material_count": count_keyword(output_lines, "*user material"),
        "validation_output_intervals": ";".join(format(v, ".12g") for v in out_intervals),
        "validation_temperature": temp_value,
        "validation_amplitude_end_time": amplitude_end_time_value(output_lines, cfg.BOUNDARY_AMPLITUDE_NAME),
        "validation_amplitude_points": json.dumps(
            amplitude_point_values(output_lines, cfg.BOUNDARY_AMPLITUDE_NAME),
            ensure_ascii=False,
        ),
        "validation_static_values": ";".join(format(v, ".12g") for v in (static_data_values(output_lines) or [])),
        "validation_target_boundary_hits": len(boundary_hits),
        "validation_material_prefix": cfg.MATERIAL_PREFIX,
        "validation_user_constants": cfg.USER_MATERIAL_CONSTANTS,
    }


def inject_lines(
    template_lines: Sequence[str],
    out_path: Path,
    df: pd.DataFrame,
    cfg: Config,
    template_name_for_validation: str,
    case: Optional[CaseItem] = None,
) -> Dict:
    lines = list(template_lines)
    if cfg.VALIDATE_ELEMENT_IDS:
        validate_injection_against_template(df, lines, template_name_for_validation)

    micro_block = generate_part_microstructure_block(df, cfg)
    material_blocks = generate_material_blocks(df, lines, cfg)

    lines2 = replace_part_microstructure(lines, micro_block, cfg)
    lines3 = replace_materials(lines2, material_blocks, cfg)

    validation_result: Dict[str, object] = {}
    if cfg.STRICT_FINAL_VALIDATION:
        validation_result = validate_final_inp(
            template_lines=lines,
            output_lines=lines3,
            df=df,
            cfg=cfg,
            case=case,
            output_name=out_path.name,
        )

    if out_path.exists() and not cfg.OVERWRITE_EXISTING_INP:
        raise FileExistsError("Output INP already exists and OVERWRITE_EXISTING_INP=False: %s" % str(out_path))
    write_text_lines(out_path, lines3)

    result = {
        "output": str(out_path),
        "n_elements_injected": int(len(df)),
        "n_bcc": int((df["Phase"] == cfg.BCC_PHASE_ID).sum()),
        "n_hcp": int((df["Phase"] == cfg.HCP_PHASE_ID).sum()),
        "n_materials": int(len(df)),
    }
    result.update(validation_result)
    return result


# =============================================================================
# 8. Template / case collection
# =============================================================================

def collect_case_templates(cfg: Config) -> List[Dict]:
    """Return list of specs: template_path, output_name, case_item or None."""
    specs: List[Dict] = []
    inp_dir = Path(cfg.INPUT_INP_DIR)

    if cfg.ENABLE_CASE_CONTROL:
        if cfg.GENERATE_CASES_FROM_SINGLE_TEMPLATE:
            base = Path(cfg.BASE_TEMPLATE_INP)
            if not base.exists():
                raise FileNotFoundError("BASE_TEMPLATE_INP not found: %s" % str(base))
            for c in CASES:
                specs.append({"template_path": base, "output_name": c.filename, "case": c})
            return specs

        if not inp_dir.exists():
            raise FileNotFoundError("INPUT_INP_DIR does not exist: %s" % str(inp_dir))

        for c in CASES:
            p = inp_dir / c.filename
            if not p.exists():
                msg = "Case template not found: %s" % str(p)
                if cfg.REQUIRE_ALL_CASE_TEMPLATES:
                    raise FileNotFoundError(msg)
                print(">> [Warn]", msg)
                continue
            specs.append({"template_path": p, "output_name": c.filename, "case": c})
        return specs

    # No case control: preserve older behavior.
    if cfg.TEMPLATE_INP_FILES:
        files = [inp_dir / name for name in cfg.TEMPLATE_INP_FILES]
    else:
        files = sorted(inp_dir.glob("*.inp"))
    if not files:
        raise FileNotFoundError("No template INP files found in: %s" % str(inp_dir))
    missing = [str(p) for p in files if not p.exists()]
    if missing:
        raise FileNotFoundError("Template INP files not found: %s" % missing)
    for p in files:
        specs.append({"template_path": p, "output_name": p.name, "case": None})
    return specs


def case_to_summary_dict(c: Optional[CaseItem], cfg: Config) -> Dict:
    if c is None:
        return {}
    return {
        "case_id": c.case_id,
        "rate_tag": c.rate_tag,
        "temp_tag": c.temp_tag,
        "temperature": c.temperature,
        "amp_end_time": c.amp_end_time,
        "amplitude_points": json.dumps(c.amplitude_points, ensure_ascii=False),
        "static_line": c.static_line,
        "output_interval": c.output_interval,
        "boundary_line": c.boundary_line,
    }


# =============================================================================
# 9. Main
# =============================================================================

def main(cfg: Config = CFG) -> None:
    input_dir = Path(cfg.INPUT_INP_DIR)
    rve_root = Path(cfg.RVE_INFO_ROOT)
    base_out_root = Path(cfg.OUTPUT_ROOT)
    out_root = (
        base_out_root / cfg.ACTIVE_LOAD_GROUP
        if cfg.ADD_LOAD_GROUP_SUBDIR
        else base_out_root
    )

    if not rve_root.exists():
        raise FileNotFoundError("RVE_INFO_ROOT does not exist: %s" % str(rve_root))

    if cfg.CLEAR_OUTPUT_ROOT_ON_START and out_root.exists():
        shutil.rmtree(out_root)
    ensure_dir(out_root)

    if cfg.AUTO_DETECT_RVES:
        rve_ids = detect_rve_ids(rve_root)
    else:
        rve_ids = normalize_rve_ids(cfg.RVE_IDS)
    if not rve_ids:
        raise RuntimeError("No RVE IDs to process.")

    template_specs = collect_case_templates(cfg)

    print("=" * 90)
    print("04_inject_rve_info_to_inp_with_4loadgroups_strict.py")
    print("Input INP dir                 :", str(input_dir))
    print("Base template                 :", str(Path(cfg.BASE_TEMPLATE_INP)))
    print("Generate from single template :", cfg.GENERATE_CASES_FROM_SINGLE_TEMPLATE)
    print("Case control enabled          :", cfg.ENABLE_CASE_CONTROL)
    print("RVE info root                 :", str(rve_root))
    print("Output root                   :", str(out_root))
    print("Active load group             :", cfg.ACTIVE_LOAD_GROUP)
    print("RVE IDs                       :", rve_ids)
    print("Cases/templates               :", len(template_specs))
    print("Boundary target               : *Boundary amplitude=%s, node=%s" % (cfg.BOUNDARY_AMPLITUDE_NAME, cfg.BOUNDARY_TARGET_NAME))
    for spec in template_specs:
        c = spec["case"]
        if c is None:
            print("  -", spec["output_name"])
        else:
            print("  - %-15s | T=%s | AMP=%s | Static=%s | Output=%s | BC=%s" % (
                spec["output_name"], c.temperature, c.amplitude_points, c.static_line, c.output_interval, c.boundary_line
            ))
    print("=" * 90)

    summary_rows: List[Dict] = []
    case_summary_rows: List[Dict] = []

    for rve_id in rve_ids:
        rve_name = normalize_rve_name(rve_id)
        table_path = rve_root / rve_name / "inp_injection_table.csv"
        df = load_injection_table(table_path, cfg)

        rve_out = out_root / rve_name
        ensure_dir(rve_out)

        if cfg.WRITE_RVE_LOCAL_COPY_OF_INJECTION_TABLE:
            df.to_csv(rve_out / "inp_injection_table_used.csv", index=False)

        print("\nProcessing %s" % rve_name)
        print("  Injection table:", str(table_path))
        print("  Elements       :", len(df))
        print("  BCC/HCP        : %d / %d" % (
            int((df["Phase"] == cfg.BCC_PHASE_ID).sum()),
            int((df["Phase"] == cfg.HCP_PHASE_ID).sum()),
        ))

        generated_files: List[str] = []

        for spec in template_specs:
            template_path: Path = spec["template_path"]
            output_name: str = spec["output_name"]
            c: Optional[CaseItem] = spec["case"]

            lines = read_text_lines(template_path)
            case_counts: Dict[str, int] = {}
            if cfg.ENABLE_CASE_CONTROL and c is not None:
                lines, case_counts = apply_case_control(lines, c, cfg)

            out_path = rve_out / output_name
            result = inject_lines(lines, out_path, df, cfg, template_path.name, case=c)
            generated_files.append(str(out_path))

            result["load_group"] = cfg.ACTIVE_LOAD_GROUP
            result["RVE_ID"] = rve_id
            result["RVE_Name"] = rve_name
            result["template_file"] = str(template_path)
            result["output_file"] = str(out_path)
            result.update(case_to_summary_dict(c, cfg))
            for k, v in case_counts.items():
                result["case_replace_" + k] = v
            summary_rows.append(result)

            if c is not None:
                row = {"RVE_Name": rve_name, "output_file": str(out_path)}
                row.update(case_to_summary_dict(c, cfg))
                row.update({"replace_" + k: v for k, v in case_counts.items()})
                case_summary_rows.append(row)

            print("  generated:", str(out_path))

        meta = {
            "RVE_ID": rve_id,
            "RVE_Name": rve_name,
            "injection_table": str(table_path),
            "n_templates": len(template_specs),
            "n_elements": int(len(df)),
            "n_bcc": int((df["Phase"] == cfg.BCC_PHASE_ID).sum()),
            "n_hcp": int((df["Phase"] == cfg.HCP_PHASE_ID).sum()),
            "case_control_enabled": cfg.ENABLE_CASE_CONTROL,
            "boundary_target_name": cfg.BOUNDARY_TARGET_NAME,
            "generated_inp_files": generated_files,
        }
        with open(rve_out / "rve_inp_generation_info.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)

    if cfg.WRITE_SUMMARY_CSV:
        summary_path = out_root / "04_injection_summary.csv"
        with open(summary_path, "w", newline="", encoding="utf-8") as f:
            fieldnames = sorted(set().union(*(row.keys() for row in summary_rows))) if summary_rows else []
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(summary_rows)
        print("\nSummary CSV:", str(summary_path))

    if cfg.WRITE_CASE_CONTROL_SUMMARY and case_summary_rows:
        case_summary_path = out_root / "04_case_control_summary.csv"
        with open(case_summary_path, "w", newline="", encoding="utf-8") as f:
            fieldnames = sorted(set().union(*(row.keys() for row in case_summary_rows)))
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(case_summary_rows)
        print("Case control CSV:", str(case_summary_path))

    print("\nDone.")
    print("Generated %d INP files." % len(summary_rows))
    print("Output root:", str(out_root))
    print("=" * 90)


if __name__ == "__main__":
    main(CFG)
